/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.lang.*;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Ruwan
 */
public class Badorder extends javax.swing.JInternalFrame {

    /**
     * Creates new form Badorder
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    String quantity;
    String buyprice;
    
    public Badorder() {
        initComponents();
         conn=DBConnect.connect();
         lordItemNumber();
         badstockLord();
         lordDisable();
         
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbadstock = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtitemname = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        txttotprice = new javax.swing.JTextField();
        cmbreitem = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(880, 510));
        setPreferredSize(new java.awt.Dimension(880, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(880, 510));
        jPanel1.setLayout(null);

        tblbadstock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbadstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbadstockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbadstock);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(310, 110, 452, 180);

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 100, 470, 210);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel6.setText("Receiving No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 350, 110, 21);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel7.setText("Item Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 380, 90, 21);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel8.setText("Quantity");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 410, 80, 21);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel9.setText("Total Price");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(310, 440, 85, 21);

        txtitemname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtitemname);
        txtitemname.setBounds(420, 380, 160, 23);

        txtquantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtquantityKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtquantityKeyTyped(evt);
            }
        });
        jPanel1.add(txtquantity);
        txtquantity.setBounds(420, 410, 160, 23);

        txttotprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txttotprice);
        txttotprice.setBounds(420, 440, 160, 23);

        cmbreitem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbreitem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Receive No" }));
        cmbreitem.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbreitemPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(cmbreitem);
        cmbreitem.setBounds(420, 350, 160, 23);

        btnDelete.setBackground(new java.awt.Color(193, 222, 136));
        btnDelete.setPreferredSize(new java.awt.Dimension(90, 40));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-24.png"))); // NOI18N
        jLabel2.setText("Delete");

        javax.swing.GroupLayout btnDeleteLayout = new javax.swing.GroupLayout(btnDelete);
        btnDelete.setLayout(btnDeleteLayout);
        btnDeleteLayout.setHorizontalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnDeleteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        btnDeleteLayout.setVerticalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDeleteLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(btnDelete);
        btnDelete.setBounds(640, 380, 90, 40);

        btnAdd.setBackground(new java.awt.Color(193, 222, 136));
        btnAdd.setPreferredSize(new java.awt.Dimension(90, 40));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-image-24.png"))); // NOI18N
        jLabel1.setText("Add");

        javax.swing.GroupLayout btnAddLayout = new javax.swing.GroupLayout(btnAdd);
        btnAdd.setLayout(btnAddLayout);
        btnAddLayout.setHorizontalGroup(
            btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnAddLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        btnAddLayout.setVerticalGroup(
            btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAddLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(btnAdd);
        btnAdd.setBounds(640, 330, 90, 40);

        btnReturn.setBackground(new java.awt.Color(193, 222, 136));
        btnReturn.setPreferredSize(new java.awt.Dimension(90, 40));
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/undo-4-24.png"))); // NOI18N
        jLabel10.setText("Return");

        javax.swing.GroupLayout btnReturnLayout = new javax.swing.GroupLayout(btnReturn);
        btnReturn.setLayout(btnReturnLayout);
        btnReturnLayout.setHorizontalGroup(
            btnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnReturnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnReturnLayout.setVerticalGroup(
            btnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(btnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnReturnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnReturn);
        btnReturn.setBounds(640, 430, 90, 40);

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 320, 470, 170);

        jPanel2.setBackground(new java.awt.Color(193, 222, 136));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bad Order List");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(300, 20, 550, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lordDisable()
    {
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(false);
        btnReturn.setEnabled(false);
        txtquantity.setEnabled(false);
        txttotprice.setEditable(false);

    }
   
    private void  theader()
    {
        JTableHeader thead = tblbadstock.getTableHeader();
        thead.setForeground(Color.BLUE);
        thead.setFont(new Font("Tahome", Font.BOLD, 14));
    }
    
    private void badstockLord()
    {
        try {
            String sql="SELECT `receive_number` as 'RECEIVE NO', `item_name` as 'ITEM NAME', `quantity` as 'QUANTITY', `total_price` as 'TOTAL PRICE' FROM `returnStock` WHERE mark=1";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblbadstock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            theader();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void lordItemNumber()
    {
        try {
            String sql="SELECT receive_no from receivestock where mark=1";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next())
             {
             String name=rs.getString("receive_no");
             cmbreitem.addItem(name);
             }
        } catch (Exception e) {
        }
    }
   
    private void cmbreitemPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbreitemPopupMenuWillBecomeInvisible
       
        if(cmbreitem.getSelectedIndex()>0)
        {
            try {
            String sql="SELECT item_name,quentity,buying_price from receivestock where receive_no='"+cmbreitem.getSelectedItem().toString()+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
               while(rs.next())
                {
                    String name=rs.getString("item_name");
                    txtitemname.setText(name);
                    quantity=rs.getString("quentity");
                    buyprice=rs.getString("buying_price");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
                }
            txtquantity.setEnabled(true);
        }
    }//GEN-LAST:event_cmbreitemPopupMenuWillBecomeInvisible

    private void txtquantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquantityKeyTyped
       
       char c=evt.getKeyChar();
       if(Character.isLetter(c)&& !evt.isAltDown())
        {
          evt.consume();
        }   
    }//GEN-LAST:event_txtquantityKeyTyped

    private void txtquantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquantityKeyReleased
      Double price=Double.parseDouble(buyprice);
      Double typeQuantity=Double.parseDouble(txtquantity.getText());
      Double totPrice=price*typeQuantity;
      txttotprice.setText(totPrice.toString());
      btnAdd.setEnabled(true);
    }//GEN-LAST:event_txtquantityKeyReleased

    private void tblbadstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbadstockMouseClicked
      
        DefaultTableModel tmodel=(DefaultTableModel)tblbadstock.getModel();
        int selectrowindex=tblbadstock.getSelectedRow();
        cmbreitem.setSelectedItem(tmodel.getValueAt(selectrowindex, 0).toString());
        btnDelete.setEnabled(true);
        btnReturn.setEnabled(true);
    }//GEN-LAST:event_tblbadstockMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
         String reno=cmbreitem.getSelectedItem().toString();
      String itname=txtitemname.getText();
      String qua=txtquantity.getText();
      String totp=txttotprice.getText();
        try {
           String sq="INSERT INTO returnStock(receive_number, item_name, quantity, total_price, mark) VALUES ('"+reno+"','"+itname+"','"+qua+"','"+totp+"',1)";
           pst=conn.prepareStatement(sq);
           pst.execute();
           JOptionPane.showMessageDialog(rootPane, "Successfully insert");
           badstockLord();
        } catch (Exception e) {
           JOptionPane.showMessageDialog(rootPane, e);
        }
      stockupdate();
      txtitemname.setText("");
      txtquantity.setText("");
      txttotprice.setText("");
      cmbreitem.removeAllItems();
      lordItemNumber();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        delete();
        cmbreitem.removeAllItems();
        lordItemNumber();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseClicked
       badReturn();
        badstockLord(); 
        cmbreitem.removeAllItems();
        lordItemNumber();
    }//GEN-LAST:event_btnReturnMouseClicked

    private void delete()
    {
        int x=JOptionPane.showConfirmDialog(rootPane, "Do you realy want to delete");
        if(x==0)
        {
        try {
                String sql="DELETE FROM returnStock where receive_number='"+ cmbreitem.getSelectedItem().toString() +"'";
                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(rootPane, "successfully deleted");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,e);
            }
        badstockLord();
        }
    }
    
    private void stockupdate()
    {
        String totvalue=txttotprice.getText();
        try {
            String squpdate = "UPDATE receivestock SET quentity=quentity -'"+txtquantity.getText()+"', total_price=total_price-'"+totvalue+"' WHERE receive_no='"+cmbreitem.getSelectedItem().toString()+"'";
            pst=conn.prepareStatement(squpdate);
            pst.execute();  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,e);              
            }
    }
      
    private  void badReturn()
    {
        try {
            String squpdate = "UPDATE returnstock SET mark=mark -1 WHERE receive_number='"+cmbreitem.getSelectedItem().toString()+"'";
            pst=conn.prepareStatement(squpdate);
            pst.execute();  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);              
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAdd;
    private javax.swing.JPanel btnDelete;
    private javax.swing.JPanel btnReturn;
    private javax.swing.JComboBox<String> cmbreitem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbadstock;
    private javax.swing.JTextField txtitemname;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txttotprice;
    // End of variables declaration//GEN-END:variables
}
