/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.lang.*;
import java.sql.Connection; 
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;  
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
///////import net.connectcode.Code128Auto;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ruwan
 */
public class cashPay extends javax.swing.JFrame {

      Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    String test;
    
    
    /**
     * Creates new form cashPay
     */
    public cashPay() {
        initComponents();
        conn=DBConnect.connect();
        txtcash.setFocusable(true);
        btnbillprint.setEnabled(false);
        btnsubmit.setEnabled(false);
        btnfinish.setEnabled(false);  
        billHeder();
        sele_to_bill();
      //  this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));        
      //  BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
     //   bi.setNorthPane(null);
        
       // txtcash.setText(Sale.sino);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttsa = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblbal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcash = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblpayble = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdisamount = new javax.swing.JTextField();
        txtdispra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btnbillprint = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnfinish = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btncancel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblinvoice = new javax.swing.JLabel();
        lblcost = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAYMENT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 14, 240, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Amount Due");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 110, 130, 22);

        txttsa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txttsa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txttsa.setText("00.00");
        jPanel1.add(txttsa);
        txttsa.setBounds(70, 130, 170, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Balance");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 170, 130, 30);

        lblbal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblbal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbal.setText("00.00");
        jPanel1.add(lblbal);
        lblbal.setBounds(80, 200, 150, 44);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Cash");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 290, 90, 22);

        txtcash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtcash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcashFocusGained(evt);
            }
        });
        txtcash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcashKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcashKeyReleased(evt);
            }
        });
        jPanel1.add(txtcash);
        txtcash.setBounds(240, 280, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("%");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(370, 190, 20, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Amount");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(364, 160, 50, 15);

        lblpayble.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpayble.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpayble.setText("0.0");
        jPanel1.add(lblpayble);
        lblpayble.setBounds(270, 220, 90, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Payble");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(370, 220, 40, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Discount");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 140, 90, 14);

        txtdisamount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdisamount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdisamount.setText("0.0");
        txtdisamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdisamountActionPerformed(evt);
            }
        });
        txtdisamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdisamountKeyReleased(evt);
            }
        });
        jPanel1.add(txtdisamount);
        txtdisamount.setBounds(270, 160, 90, 26);

        txtdispra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdispra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdispra.setText("0");
        txtdispra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdispraKeyReleased(evt);
            }
        });
        jPanel1.add(txtdispra);
        txtdispra.setBounds(270, 190, 90, 26);

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 80, 370, 180);

        txtbill.setEditable(false);
        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane1.setViewportView(txtbill);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(460, 90, 250, 300);

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(450, 80, 270, 320);

        btnbillprint.setBackground(new java.awt.Color(193, 222, 136));
        btnbillprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbillprintMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer-24.png"))); // NOI18N
        jLabel13.setText("Print");

        javax.swing.GroupLayout btnbillprintLayout = new javax.swing.GroupLayout(btnbillprint);
        btnbillprint.setLayout(btnbillprintLayout);
        btnbillprintLayout.setHorizontalGroup(
            btnbillprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btnbillprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnbillprintLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnbillprintLayout.setVerticalGroup(
            btnbillprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnbillprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnbillprintLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnbillprint);
        btnbillprint.setBounds(160, 330, 90, 30);

        btnfinish.setBackground(new java.awt.Color(193, 222, 136));
        btnfinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfinishMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/warning-38-24.png"))); // NOI18N
        jLabel14.setText("Finish");

        javax.swing.GroupLayout btnfinishLayout = new javax.swing.GroupLayout(btnfinish);
        btnfinish.setLayout(btnfinishLayout);
        btnfinishLayout.setHorizontalGroup(
            btnfinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btnfinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnfinishLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnfinishLayout.setVerticalGroup(
            btnfinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnfinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnfinishLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnfinish);
        btnfinish.setBounds(160, 370, 90, 30);

        btnsubmit.setBackground(new java.awt.Color(193, 222, 136));
        btnsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsubmitMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-image-24.png"))); // NOI18N
        jLabel15.setText("Submit");

        javax.swing.GroupLayout btnsubmitLayout = new javax.swing.GroupLayout(btnsubmit);
        btnsubmit.setLayout(btnsubmitLayout);
        btnsubmitLayout.setHorizontalGroup(
            btnsubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btnsubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnsubmitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnsubmitLayout.setVerticalGroup(
            btnsubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnsubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnsubmitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnsubmit);
        btnsubmit.setBounds(310, 330, 90, 30);

        btncancel.setBackground(new java.awt.Color(193, 222, 136));
        btncancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_25px.png"))); // NOI18N
        jLabel16.setText("Cancel");

        javax.swing.GroupLayout btncancelLayout = new javax.swing.GroupLayout(btncancel);
        btncancel.setLayout(btncancelLayout);
        btncancelLayout.setHorizontalGroup(
            btncancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btncancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btncancelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btncancelLayout.setVerticalGroup(
            btncancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btncancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btncancelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btncancel);
        btncancel.setBounds(310, 370, 90, 30);
        jPanel1.add(lblinvoice);
        lblinvoice.setBounds(390, 10, 70, 0);
        jPanel1.add(lblcost);
        lblcost.setBounds(390, 40, 40, 0);

        jPanel2.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 10, 670, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtcashFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcashFocusGained

    }//GEN-LAST:event_txtcashFocusGained

    private void txtcashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcashKeyReleased

        if(txtcash.getText().length()>0)
        {
        
        Double amount=Double.parseDouble(txttsa.getText());
        Double cash=Double.parseDouble(txtcash.getText());
        Double discount=Double.parseDouble(txtdisamount.getText());
        Double afDiAmount=amount-discount;
        Double bal=cash-afDiAmount;
        lblbal.setText(bal.toString());
        }
        else
        {
            lblbal.setText("00.00");
        }
    }//GEN-LAST:event_txtcashKeyReleased

    private void txtcashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcashKeyPressed
      btnsubmit.setEnabled(true);
    }//GEN-LAST:event_txtcashKeyPressed

    private void txtdisamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdisamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdisamountActionPerformed

    private void txtdispraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdispraKeyReleased
    if(txtdispra.getText().length()>0)
    {
       Double totalAmount=Double.valueOf(txttsa.getText());
       Double disPra=Double.valueOf(txtdispra.getText());
       Double disValue=totalAmount*(disPra/100);
       Double payble=totalAmount-disValue;
       lblpayble.setText(payble.toString());
       txtdisamount.setText(disValue.toString());
    }
    else
    {
        txtdisamount.setText("0.0");
    }
    }//GEN-LAST:event_txtdispraKeyReleased

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        
    }//GEN-LAST:event_formFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         String test=Sale.saleincome;
         txttsa.setText(test);
         lblpayble.setText(test);
    }//GEN-LAST:event_formWindowOpened

    private void txtdisamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdisamountKeyReleased
               
       if(txtdisamount.getText().length()>0)
       {
       Double totalAmount=Double.valueOf(txttsa.getText());
       // Double disPra=Double.valueOf(txtdispra.getText());
       Double disVal=Double.parseDouble(txtdisamount.getText());
       // Double disValue=totalAmount-disVal;
       Double payble=totalAmount-disVal;
       lblpayble.setText(payble.toString());
       // txtdisamount.setText(disValue.toString());      
       }
       else
       {
        txtdisamount.setText("0.0");
       }         
    }//GEN-LAST:event_txtdisamountKeyReleased

    private void btnbillprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbillprintMouseClicked
       try {
            txtbill.print();
        } catch (Exception e) {
        }
        
        this.dispose(); 
    }//GEN-LAST:event_btnbillprintMouseClicked

    private void btnfinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfinishMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnfinishMouseClicked

    private void btnsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseClicked
        String sinum=Sale.sino;
        //  String sainc=Sale.saleincome;
        String sainc=lblpayble.getText();
        String sacos=Sale.salecost;
        String dis=txtdisamount.getText();
        String cash=txtcash.getText();
        String bal=lblbal.getText();
        String time=Home.time;
        String date=Home.date;

        try {
            String qr= "INSERT INTO payment(sin,sale_income,sale_cost,discount, cash, balance, date, time,sale_return, return_cost) VALUES ('"+sinum+"','"+sainc+"','"+sacos+"','"+dis+"','"+cash+"','"+bal+"','"+date+"','"+time+"','0','0')";
            pst=conn.prepareStatement(qr);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Item added successfully");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }
        btnsubmit.setEnabled(false);
        btncancel.setEnabled(false);
        btnbillprint.setEnabled(true);
        btnfinish.setEnabled(true); 
        
        
        
        try {
            
            txtbill.setText(txtbill.getText()
                    +"-------------------------------------"+"\n"
                    +"Total \t"+txttsa.getText()+"\n"
                    +"Discount \t"+txtdisamount.getText()+"\n"
                    +"-------------------------------------"+"\n"
                    +"Payble \t"+lblpayble.getText()+"\n"
                    +"Cash \t"+txtcash.getText()+"\n"
                    +"-------------------------------------"+"\n"
                    +"Balance \t"+lblbal.getText()+"\n"
                    +"========================"+"\n"
        +login.dev_name+"\n\n");
            
        } catch (Exception e) {
        }  
        
    }//GEN-LAST:event_btnsubmitMouseClicked

    private void btncancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btncancelMouseClicked

    String iName;
    String iQuentity;
    String iPrice;
    String iAmount;
    
    
    
    private void sele_to_bill()
    {
     try{
       // String si=Sale.sino;  
        String sql="SELECT `tid`, `sin`, `receive_no`, `item_number`, `item_name`, `quentity`, `price`, `amount` FROM `sells` WHERE sin='"+Sale.sino+"'";
        pst=conn.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next())
             {
                iName=rs.getString("item_name");  
                iQuentity=rs.getString("quentity");
                iPrice=rs.getString("price");
                iAmount=rs.getString("amount");
               
               bill();
               
             }
//             else
//             {
//             JOptionPane.showMessageDialog(rootPane, "incorect");
//             }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(rootPane, e);
        }
    
    }
    
    private void bill()
    {
    
         txtbill.setText(
        txtbill.getText()+ iName +"\t \n      "+iQuentity+"*"+iPrice+" -\t"+iAmount+"\n"
        );
    
    }
    
      private void billHeder()
    {
    
    txtbill.setText("========================"+"\n"
                +login.com_name+"\n"
        +login.con_num+"\n"
            +login.email+"\n"
        +login.adress+"\n"
        +"========================"+"\n");
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashPay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnbillprint;
    private javax.swing.JPanel btncancel;
    private javax.swing.JPanel btnfinish;
    private javax.swing.JPanel btnsubmit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbal;
    private javax.swing.JLabel lblcost;
    private javax.swing.JLabel lblinvoice;
    private javax.swing.JLabel lblpayble;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtcash;
    private javax.swing.JTextField txtdisamount;
    private javax.swing.JTextField txtdispra;
    private javax.swing.JLabel txttsa;
    // End of variables declaration//GEN-END:variables
}
