/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.lang.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruwan
 */
public class Edite extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    /**
     * Creates new form Edite
     */
    public Edite() {
        initComponents();
        conn=DBConnect.connect();
        detailsSelect();

    }
private void detailsSelect()
    {
        String sq="SELECT * from developer";
        try {
             pst=conn.prepareStatement(sq);
                rs=pst.executeQuery();
                while(rs.next())
                {
                    String com_name=rs.getString("company_name");
                    String sub_title=rs.getString("sub_title");
                    String ex_date=rs.getString("ex_date");
                    String dev_name=rs.getString("deve_name");
                    String bill_heder=rs.getString("bill_heder");
                    String contac_no=rs.getString("contac_no");
                    
                    String email=rs.getString("email");
                    String adress=rs.getString("adress");
                    
                  
                    txtcomname.setText(com_name);
                    txtsubti.setText(sub_title);
                    txtexdate.setText(ex_date);
                    txtdev.setText(dev_name);
                    txtbillhed.setText(bill_heder);
                    txtcontac.setText(contac_no);
                    txtemail.setText(email);
                    txtadress.setText(adress);
                }
        } catch (Exception e) {
        }
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcomname = new javax.swing.JTextField();
        txtsubti = new javax.swing.JTextField();
        txtexdate = new javax.swing.JTextField();
        txtdev = new javax.swing.JTextField();
        txtbillhed = new javax.swing.JTextField();
        txtcontac = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtadress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel6.setText("Company Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 110, 110, 20);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel7.setText("Sub Tittle");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 140, 80, 20);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel8.setText("Ex Date");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 310, 70, 20);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel9.setText("Developer");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 350, 80, 20);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel10.setText("Bill Header");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 170, 90, 20);

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel11.setText("Contac No");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 200, 90, 20);

        txtcomname.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(txtcomname);
        txtcomname.setBounds(159, 110, 300, 24);

        txtsubti.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(txtsubti);
        txtsubti.setBounds(159, 140, 300, 24);

        txtexdate.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(txtexdate);
        txtexdate.setBounds(160, 310, 300, 24);

        txtdev.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txtdev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdevActionPerformed(evt);
            }
        });
        jPanel1.add(txtdev);
        txtdev.setBounds(160, 350, 300, 24);

        txtbillhed.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(txtbillhed);
        txtbillhed.setBounds(160, 170, 300, 24);

        txtcontac.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(txtcontac);
        txtcontac.setBounds(160, 200, 300, 24);

        btnupdate.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-validated-icon (1).png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(330, 400, 120, 40);

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 390, 450, 60);

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel13.setText("Email");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 230, 90, 20);

        txtemail.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(txtemail);
        txtemail.setBounds(160, 230, 300, 24);

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel14.setText("Adress");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 280, 90, 20);

        txtadress.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(txtadress);
        txtadress.setBounds(160, 280, 300, 24);

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 70, 450, 320);

        jPanel2.setBackground(new java.awt.Color(193, 222, 136));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Content Edit");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_25px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        try {
            String squpdate = "UPDATE `developer` SET `company_name`='"+txtcomname.getText()+"',`sub_title`='"+txtsubti.getText()+"',`ex_date`='"+txtexdate.getText()+"',`deve_name`='"+txtdev.getText()+"',`bill_heder`='"+txtbillhed.getText()+"',`contac_no`='"+txtcontac.getText()+"',`email`='"+txtemail.getText()+"',`adress`='"+txtadress.getText()+"'";
            pst=conn.prepareStatement(squpdate);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"successfuly update");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtdevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdevActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
      Home ho=new Home();
      ho.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtadress;
    private javax.swing.JTextField txtbillhed;
    private javax.swing.JTextField txtcomname;
    private javax.swing.JTextField txtcontac;
    private javax.swing.JTextField txtdev;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtexdate;
    private javax.swing.JTextField txtsubti;
    // End of variables declaration//GEN-END:variables
}
