/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import static java.awt.SystemColor.menu;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ccs
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    int x,y;
    public static String date;
    public static String time;
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    int id=0;
    
    Color slidpane;
    Color slidmark;
    Color btnback;
    Color btnclick;
    
    int id1;
    int id2;
    int id3;
    
              
    
    
    public Home() {
        initComponents();
        btnhide.hide();
     //   conn = DBConnect.connect();
        clock();
        slidpane =new Color(39, 115, 87);
        slidmark = new Color(124, 25, 83);
        btnback = new Color(39, 115, 87);
        btnclick = new Color(46, 149, 152);
        menuss.setPreferredSize( new Dimension(180, 560) );
        
       Main ma = new Main();
       jDesktopPane1.add(ma).setVisible(true);
       
       lbluname.setText(login.uname);
        
   //      Main ap =new Main();
   //    jDesktopPane1.add(ap).setVisible(true);
   //     homeLord();
        
        
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbluname = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel10 = new javax.swing.JPanel();
        menuss = new javax.swing.JPanel();
        btn1 = new javax.swing.JPanel();
        btpane1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn2 = new javax.swing.JPanel();
        btpane2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn3 = new javax.swing.JPanel();
        btpane3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn4 = new javax.swing.JPanel();
        btpane5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn5 = new javax.swing.JPanel();
        btpane4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn6 = new javax.swing.JPanel();
        btpane6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnhide = new javax.swing.JLabel();
        btnshow = new javax.swing.JLabel();
        btn7 = new javax.swing.JPanel();
        btpane7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn8 = new javax.swing.JPanel();
        btpane8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn10 = new javax.swing.JPanel();
        btpane10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btn9 = new javax.swing.JPanel();
        btpane9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imgp1 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        imgp2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        imgp3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1010, 590));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(193, 222, 136));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 30));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_25px.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1035, Short.MAX_VALUE)
                .addComponent(jLabel21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 30);

        jPanel3.setBackground(new java.awt.Color(193, 222, 136));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Contacts_25px.png"))); // NOI18N

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltime.setForeground(new java.awt.Color(255, 255, 255));
        lbltime.setText("Time");

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldate.setText("Date");

        lbluname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbluname.setForeground(new java.awt.Color(255, 255, 255));
        lbluname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(lbltime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbluname, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbluname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbltime)
                                .addComponent(lbldate))
                            .addComponent(jLabel20))))
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(410, 30, 630, 50);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(180, 80, 880, 510);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuss.setBackground(new java.awt.Color(193, 222, 136));
        menuss.setMinimumSize(new java.awt.Dimension(10, 100));

        btn1.setBackground(new java.awt.Color(193, 222, 136));
        btn1.setPreferredSize(new java.awt.Dimension(99, 30));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn1MousePressed(evt);
            }
        });
        btn1.setLayout(null);

        btpane1.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout btpane1Layout = new javax.swing.GroupLayout(btpane1);
        btpane1.setLayout(btpane1Layout);
        btpane1Layout.setHorizontalGroup(
            btpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        btpane1Layout.setVerticalGroup(
            btpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn1.add(btpane1);
        btpane1.setBounds(0, 0, 8, 30);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");
        btn1.add(jLabel2);
        jLabel2.setBounds(72, 11, 60, 18);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-3-24.png"))); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(30, 30));
        btn1.add(jLabel14);
        jLabel14.setBounds(10, 0, 30, 30);

        btn2.setBackground(new java.awt.Color(193, 222, 136));
        btn2.setPreferredSize(new java.awt.Dimension(99, 30));
        btn2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn2MouseMoved(evt);
            }
        });
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn2MouseReleased(evt);
            }
        });
        btn2.setLayout(null);

        btpane2.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout btpane2Layout = new javax.swing.GroupLayout(btpane2);
        btpane2.setLayout(btpane2Layout);
        btpane2Layout.setHorizontalGroup(
            btpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        btpane2Layout.setVerticalGroup(
            btpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn2.add(btpane2);
        btpane2.setBounds(0, 0, 8, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add Items");
        btn2.add(jLabel3);
        jLabel3.setBounds(72, 11, 90, 17);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-image-24.png"))); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(30, 30));
        btn2.add(jLabel15);
        jLabel15.setBounds(10, 0, 30, 30);

        btn3.setBackground(new java.awt.Color(193, 222, 136));
        btn3.setPreferredSize(new java.awt.Dimension(99, 30));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn3MousePressed(evt);
            }
        });
        btn3.setLayout(null);

        btpane3.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout btpane3Layout = new javax.swing.GroupLayout(btpane3);
        btpane3.setLayout(btpane3Layout);
        btpane3Layout.setHorizontalGroup(
            btpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        btpane3Layout.setVerticalGroup(
            btpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn3.add(btpane3);
        btpane3.setBounds(0, 0, 8, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Stock");
        btn3.add(jLabel4);
        jLabel4.setBounds(70, 10, 70, 17);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stack-24.png"))); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(30, 30));
        btn3.add(jLabel16);
        jLabel16.setBounds(10, 0, 30, 30);

        btn4.setBackground(new java.awt.Color(193, 222, 136));
        btn4.setPreferredSize(new java.awt.Dimension(99, 30));
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn4MousePressed(evt);
            }
        });
        btn4.setLayout(null);

        btpane5.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout btpane5Layout = new javax.swing.GroupLayout(btpane5);
        btpane5.setLayout(btpane5Layout);
        btpane5Layout.setHorizontalGroup(
            btpane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        btpane5Layout.setVerticalGroup(
            btpane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn4.add(btpane5);
        btpane5.setBounds(0, 0, 8, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sell");
        btn4.add(jLabel6);
        jLabel6.setBounds(72, 11, 60, 17);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cart-43-24.png"))); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(30, 30));
        btn4.add(jLabel17);
        jLabel17.setBounds(10, 0, 30, 30);

        btn5.setBackground(new java.awt.Color(193, 222, 136));
        btn5.setPreferredSize(new java.awt.Dimension(99, 30));
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn5MousePressed(evt);
            }
        });
        btn5.setLayout(null);

        btpane4.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout btpane4Layout = new javax.swing.GroupLayout(btpane4);
        btpane4.setLayout(btpane4Layout);
        btpane4Layout.setHorizontalGroup(
            btpane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        btpane4Layout.setVerticalGroup(
            btpane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn5.add(btpane4);
        btpane4.setBounds(0, 0, 8, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Report");
        btn5.add(jLabel5);
        jLabel5.setBounds(72, 11, 50, 17);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bar-chart-6-24.png"))); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(30, 30));
        btn5.add(jLabel18);
        jLabel18.setBounds(10, 0, 30, 30);

        btn6.setBackground(new java.awt.Color(193, 222, 136));
        btn6.setPreferredSize(new java.awt.Dimension(99, 30));
        btn6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn6MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn6MouseMoved(evt);
            }
        });
        btn6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn6FocusGained(evt);
            }
        });
        btn6.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                btn6MouseWheelMoved(evt);
            }
        });
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn6MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn6MousePressed(evt);
            }
        });
        btn6.setLayout(null);

        btpane6.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout btpane6Layout = new javax.swing.GroupLayout(btpane6);
        btpane6.setLayout(btpane6Layout);
        btpane6Layout.setHorizontalGroup(
            btpane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        btpane6Layout.setVerticalGroup(
            btpane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn6.add(btpane6);
        btpane6.setBounds(0, 0, 8, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Setting");
        btn6.add(jLabel8);
        jLabel8.setBounds(72, 11, 50, 17);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/settings-24-24.png"))); // NOI18N
        jLabel19.setPreferredSize(new java.awt.Dimension(30, 30));
        btn6.add(jLabel19);
        jLabel19.setBounds(10, 0, 30, 30);

        btnhide.setForeground(new java.awt.Color(255, 255, 255));
        btnhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/list-2-24.png"))); // NOI18N
        btnhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhideMouseClicked(evt);
            }
        });

        btnshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/list-2-24.png"))); // NOI18N
        btnshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnshowMouseClicked(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(193, 222, 136));
        btn7.setPreferredSize(new java.awt.Dimension(99, 30));
        btn7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn7MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn7MouseMoved(evt);
            }
        });
        btn7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn7FocusGained(evt);
            }
        });
        btn7.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                btn7MouseWheelMoved(evt);
            }
        });
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn7MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn7MousePressed(evt);
            }
        });
        btn7.setLayout(null);

        btpane7.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout btpane7Layout = new javax.swing.GroupLayout(btpane7);
        btpane7.setLayout(btpane7Layout);
        btpane7Layout.setHorizontalGroup(
            btpane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        btpane7Layout.setVerticalGroup(
            btpane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn7.add(btpane7);
        btpane7.setBounds(0, 0, 8, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Backup");
        btn7.add(jLabel10);
        jLabel10.setBounds(72, 11, 70, 17);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/upload-24.png"))); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(30, 30));
        btn7.add(jLabel22);
        jLabel22.setBounds(10, 0, 30, 30);

        btn8.setBackground(new java.awt.Color(193, 222, 136));
        btn8.setPreferredSize(new java.awt.Dimension(99, 30));
        btn8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn8MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn8MouseMoved(evt);
            }
        });
        btn8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn8FocusGained(evt);
            }
        });
        btn8.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                btn8MouseWheelMoved(evt);
            }
        });
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn8MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn8MousePressed(evt);
            }
        });
        btn8.setLayout(null);

        btpane8.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout btpane8Layout = new javax.swing.GroupLayout(btpane8);
        btpane8.setLayout(btpane8Layout);
        btpane8Layout.setHorizontalGroup(
            btpane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        btpane8Layout.setVerticalGroup(
            btpane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn8.add(btpane8);
        btpane8.setBounds(0, 0, 8, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Bad Order");
        btn8.add(jLabel23);
        jLabel23.setBounds(72, 11, 90, 17);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/warning-38-24.png"))); // NOI18N
        jLabel24.setPreferredSize(new java.awt.Dimension(30, 30));
        btn8.add(jLabel24);
        jLabel24.setBounds(10, 0, 30, 30);

        btn10.setBackground(new java.awt.Color(193, 222, 136));
        btn10.setPreferredSize(new java.awt.Dimension(99, 30));
        btn10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn10MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn10MouseMoved(evt);
            }
        });
        btn10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn10FocusGained(evt);
            }
        });
        btn10.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                btn10MouseWheelMoved(evt);
            }
        });
        btn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn10MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn10MousePressed(evt);
            }
        });
        btn10.setLayout(null);

        btpane10.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout btpane10Layout = new javax.swing.GroupLayout(btpane10);
        btpane10.setLayout(btpane10Layout);
        btpane10Layout.setHorizontalGroup(
            btpane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        btpane10Layout.setVerticalGroup(
            btpane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn10.add(btpane10);
        btpane10.setBounds(0, 0, 8, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Reurn to stock");
        btn10.add(jLabel25);
        jLabel25.setBounds(52, 11, 110, 17);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rotate-24-24.png"))); // NOI18N
        jLabel26.setPreferredSize(new java.awt.Dimension(30, 30));
        btn10.add(jLabel26);
        jLabel26.setBounds(10, 0, 30, 30);

        btn9.setBackground(new java.awt.Color(193, 222, 136));
        btn9.setPreferredSize(new java.awt.Dimension(99, 30));
        btn9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn9MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn9MouseMoved(evt);
            }
        });
        btn9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn9FocusGained(evt);
            }
        });
        btn9.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                btn9MouseWheelMoved(evt);
            }
        });
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn9MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn9MousePressed(evt);
            }
        });
        btn9.setLayout(null);

        btpane9.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout btpane9Layout = new javax.swing.GroupLayout(btpane9);
        btpane9.setLayout(btpane9Layout);
        btpane9Layout.setHorizontalGroup(
            btpane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        btpane9Layout.setVerticalGroup(
            btpane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn9.add(btpane9);
        btpane9.setBounds(0, 0, 8, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Sale return");
        btn9.add(jLabel27);
        jLabel27.setBounds(72, 11, 90, 17);

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/undo-4-24.png"))); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(30, 30));
        btn9.add(jLabel28);
        jLabel28.setBounds(10, 0, 30, 30);

        javax.swing.GroupLayout menussLayout = new javax.swing.GroupLayout(menuss);
        menuss.setLayout(menussLayout);
        menussLayout.setHorizontalGroup(
            menussLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menussLayout.createSequentialGroup()
                .addComponent(btnhide, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(142, 142, 142)
                .addComponent(btnshow, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
            .addGroup(menussLayout.createSequentialGroup()
                .addGroup(menussLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menussLayout.setVerticalGroup(
            menussLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menussLayout.createSequentialGroup()
                .addGroup(menussLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menussLayout.createSequentialGroup()
                        .addComponent(btnhide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(menussLayout.createSequentialGroup()
                        .addComponent(btnshow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jPanel10.add(menuss, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));
        menuss.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 250, 50));

        imgp1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        imgp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel10.add(imgp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 130, 30));
        jPanel10.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 130, 110));
        jPanel10.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 130, 110));

        imgp2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        imgp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel10.add(imgp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 130, 30));
        jPanel10.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 130, 110));

        imgp3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        imgp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel10.add(imgp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 130, 30));

        getContentPane().add(jPanel10);
        jPanel10.setBounds(0, 30, 440, 560);

        setSize(new java.awt.Dimension(1058, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
       
         x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       
         int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_jPanel1MouseDragged

    
     public void clock()
        {
        Thread clock=new Thread()
                {
                public void run()
                {
                    try {
                    while(true)    // for(; ;)
                        {                                                  
                            Calendar cal=new GregorianCalendar();
                            int day=cal.get(Calendar.DAY_OF_MONTH);
                            int month=cal.get(Calendar.MONTH)+1;
                            int year=cal.get(Calendar.YEAR);

                            int second=cal.get(Calendar.SECOND);
                            id = second=cal.get(Calendar.SECOND);
                            int minute=cal.get(Calendar.MINUTE);
                            int hour=cal.get(Calendar.HOUR);

                            time=( hour +":"+ minute +":"+ second);
                            date=( year +"-"+ month +"-"+ day ); 
                         //   lbltime.setText(time);
                                sleep(1000);
                           lbldate.setText(date);
                           lbltime.setText(time);
                                id1 = id;
                                id2 = id + 2;
                                id3 = id + 4;
                                
                             //   imageLord1();
                             //   imageLord2();
                             //   imageLord3();
                           
                        }
                    } catch (InterruptedException ex) {
                      
                    }
                }

                };
        clock.start();
 
    }

   
    
    
//    private void imageGet()
//    {
//    
//       
//        
//         try {
//            String sql="SELECT `sell_price`, `image` FROM `item` WHERE imageid='"+id+"'";          
//            pst=conn.prepareStatement(sql);
//            rs=pst.executeQuery();
//           if(rs.next())
//           {
//       //   txtsprice.setText(rs.getString("sell_price"));
//              
//               
//               byte[] imagedata=rs.getBytes("image");
//               format=new ImageIcon(imagedata);
//               Image mm=format.getImage();
//               Image img2=mm.getScaledInstance(lblimage1.getWidth(), lblimage1.getHeight(), Image.SCALE_SMOOTH);
//               ImageIcon image=new ImageIcon(img2);
//               lblimage1.setIcon(image);
//            }                            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, e);
//        }       
//    
//    }
    
//     private ImageIcon format=null;
//String fname=null;
//int s=0;
//byte[] pimage=null;
//
//      public ImageIcon resizeImage(String imagePath, byte[] pic){
//          
//        ImageIcon myImage=null;
//        if(imagePath !=null)
//        {
//        myImage=new ImageIcon(imagePath);
//        
//        }else{
//         myImage=new ImageIcon(pic);
//        }
//                
//        Image img=myImage.getImage();
//        Image img2=img.getScaledInstance(lblimage1.getHeight(), lblimage1.getWidth(),  Image.SCALE_SMOOTH);
//        ImageIcon image=new ImageIcon(img2);
//        return image;
//    } 
    
     
     
     private void imageLord1()
     {     
          try {
            String sql="SELECT `id`, `image`, `price` FROM `image` WHERE id = '"+id1+"'";          
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next())
           {
               imgp1.setText(rs.getString("price"));  
               byte[] imagedata=rs.getBytes("image");
               format=new ImageIcon(imagedata);
               Image mm=format.getImage();
               Image img2=mm.getScaledInstance(img1.getWidth(), img1.getHeight(), Image.SCALE_SMOOTH);
               ImageIcon image=new ImageIcon(img2);
               img1.setIcon(image);
            } 
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }       
     
     }
     
      private void imageLord2()
     {     
          try {
            String sql="SELECT `id`, `image`, `price` FROM `image` WHERE id = '"+id2+"'";          
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next())
           {
               imgp2.setText(rs.getString("price"));  
               byte[] imagedata=rs.getBytes("image");
               format=new ImageIcon(imagedata);
               Image mm=format.getImage();
               Image img22=mm.getScaledInstance(img2.getWidth(), img2.getHeight(), Image.SCALE_SMOOTH);
               ImageIcon image=new ImageIcon(img22);
               img2.setIcon(image);
            } 
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }       
     
     }
      
       private void imageLord3()
     {     
          try {
            String sql="SELECT `id`, `image`, `price` FROM `image` WHERE id = '"+id3+"'";          
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next())
           {
               imgp3.setText(rs.getString("price"));  
               byte[] imagedata=rs.getBytes("image");
               format=new ImageIcon(imagedata);
               Image mm=format.getImage();
               Image img22=mm.getScaledInstance(img3.getWidth(), img3.getHeight(), Image.SCALE_SMOOTH);
               ImageIcon image=new ImageIcon(img22);
               img3.setIcon(image);
            } 
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }       
     
     }
     
     
     
     
     
      private ImageIcon format=null;
String fname=null;
int s=0;
byte[] pimage=null;

      public ImageIcon resizeImage(String imagePath, byte[] pic){
          
        ImageIcon myImage=null;
        if(imagePath !=null)
        {
        myImage=new ImageIcon(imagePath);
        
        }else{
         myImage=new ImageIcon(pic);
        }
                
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(img1.getHeight(), img1.getWidth(),  Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    } 
     
    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        jDesktopPane1.removeAll();
   //     Main ap =new Main();
   //     jDesktopPane1.add(ap).setVisible(true);
        
       // btnhome.setBackground(Color.GREEN);
        
        Main ma = new Main();
       jDesktopPane1.add(ma).setVisible(true);
        
    }//GEN-LAST:event_btn1MouseClicked

    private void btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MousePressed
        
        
         homeLord();
         
         
        
    }//GEN-LAST:event_btn1MousePressed

    private void homeLord()
    {
    
        btpane1.setBackground(slidmark);
     
        btpane2.setBackground(slidpane);
        btpane3.setBackground(slidpane);
        btpane4.setBackground(slidpane);
        btpane5.setBackground(slidpane);
        btpane6.setBackground(slidpane);
        btpane7.setBackground(slidpane);
        btpane8.setBackground(slidpane);
        btpane9.setBackground(slidpane);
        btpane10.setBackground(slidpane);
        
        btn1.setBackground(btnclick);
        btn2.setBackground(slidpane);
        btn3.setBackground(slidpane);
        btn4.setBackground(slidpane);
        btn5.setBackground(slidpane);
        btn6.setBackground(slidpane);
        btn7.setBackground(slidpane);
        btn8.setBackground(slidpane);
        btn9.setBackground(slidpane);
        btn10.setBackground(slidpane);
    
    }
    
    private void btn2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseMoved
        //  btn2.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn2MouseMoved

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        jDesktopPane1.removeAll();
        recieved ap =new recieved();
       jDesktopPane1.add(ap).setVisible(true);
       
       
//         jPanel4.setPreferredSize( new Dimension(0, 510) );
//         jPanel4.revalidate();
//         jPanel4.repaint();
      
       
                

    }//GEN-LAST:event_btn2MouseClicked

    private void btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MousePressed
        btpane2.setBackground(slidmark);
        btpane1.setBackground(slidpane);
        btpane3.setBackground(slidpane);
        btpane4.setBackground(slidpane);
        btpane5.setBackground(slidpane);
        btpane6.setBackground(slidpane);
        btpane7.setBackground(slidpane);
        btpane8.setBackground(slidpane);
        btpane9.setBackground(slidpane);
        btpane10.setBackground(slidpane);
        
        btn2.setBackground(btnclick);
        btn1.setBackground(slidpane);
        btn3.setBackground(slidpane);
        btn4.setBackground(slidpane);
        btn5.setBackground(slidpane);
        btn6.setBackground(slidpane);
        btn7.setBackground(slidpane);
        btn8.setBackground(slidpane);
        btn9.setBackground(slidpane);
        btn10.setBackground(slidpane);

        //(new Color(255,0 ,51));
    }//GEN-LAST:event_btn2MousePressed

    private void btn2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseReleased

    }//GEN-LAST:event_btn2MouseReleased

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked

        jDesktopPane1.removeAll();
        Stock ap =new Stock();
        jDesktopPane1.add(ap).setVisible(true);

    }//GEN-LAST:event_btn3MouseClicked

    private void btn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MousePressed

        btpane3.setBackground(slidmark);
        btpane2.setBackground(slidpane);
        btpane1.setBackground(slidpane);
        btpane4.setBackground(slidpane);
        btpane5.setBackground(slidpane);
        btpane6.setBackground(slidpane);
        btpane7.setBackground(slidpane);
        btpane8.setBackground(slidpane);
        btpane9.setBackground(slidpane);
        btpane10.setBackground(slidpane);
        
        btn3.setBackground(btnclick);
        btn2.setBackground(slidpane);
        btn1.setBackground(slidpane);
        btn4.setBackground(slidpane);
        btn5.setBackground(slidpane);
        btn6.setBackground(slidpane);
        btn7.setBackground(slidpane);
        btn8.setBackground(slidpane);
        btn9.setBackground(slidpane);
        btn10.setBackground(slidpane);
        
    }//GEN-LAST:event_btn3MousePressed

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked

        jDesktopPane1.removeAll();
        Sale ap =new Sale();
        jDesktopPane1.add(ap).setVisible(true);
    }//GEN-LAST:event_btn4MouseClicked

    private void btn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MousePressed

        btpane5.setBackground(slidmark);
        btpane2.setBackground(slidpane);
        btpane3.setBackground(slidpane);
        btpane4.setBackground(slidpane);
        btpane1.setBackground(slidpane);
        btpane6.setBackground(slidpane);
        btpane7.setBackground(slidpane);
        btpane8.setBackground(slidpane);
        btpane9.setBackground(slidpane);
        btpane10.setBackground(slidpane);
        
        btn4.setBackground(btnclick);
        btn2.setBackground(slidpane);
        btn3.setBackground(slidpane);
        btn1.setBackground(slidpane);
        btn5.setBackground(slidpane);
        btn6.setBackground(slidpane);
        btn7.setBackground(slidpane);
        btn8.setBackground(slidpane);
        btn9.setBackground(slidpane);
        btn10.setBackground(slidpane);
    }//GEN-LAST:event_btn4MousePressed

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        jDesktopPane1.removeAll();
       Report ap =new Report();
       jDesktopPane1.add(ap).setVisible(true);
    }//GEN-LAST:event_btn5MouseClicked

    private void btn5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MousePressed

        btpane4.setBackground(slidmark);
        btpane2.setBackground(slidpane);
        btpane3.setBackground(slidpane);
        btpane1.setBackground(slidpane);
        btpane5.setBackground(slidpane);
        btpane6.setBackground(slidpane);
        btpane7.setBackground(slidpane);
        btpane8.setBackground(slidpane);
        btpane9.setBackground(slidpane);
        btpane10.setBackground(slidpane);
        
        btn5.setBackground(btnclick);
        btn2.setBackground(slidpane);
        btn3.setBackground(slidpane);
        btn4.setBackground(slidpane);
        btn1.setBackground(slidpane);
        btn6.setBackground(slidpane);
        btn7.setBackground(slidpane);
        btn8.setBackground(slidpane);
        btn9.setBackground(slidpane);
        btn10.setBackground(slidpane);
    }//GEN-LAST:event_btn5MousePressed

    private void btn6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseDragged

    }//GEN-LAST:event_btn6MouseDragged

    private void btn6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseMoved

    }//GEN-LAST:event_btn6MouseMoved

    private void btn6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn6FocusGained

    }//GEN-LAST:event_btn6FocusGained

    private void btn6MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_btn6MouseWheelMoved
        btn6.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btn6MouseWheelMoved

    private void btn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseEntered

    }//GEN-LAST:event_btn6MouseEntered

    private void btn6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MousePressed
        btpane6.setBackground(slidmark);
        btpane2.setBackground(slidpane);
        btpane3.setBackground(slidpane);
        btpane1.setBackground(slidpane);
        btpane5.setBackground(slidpane);
        btpane4.setBackground(slidpane);
        btpane7.setBackground(slidpane);
        btpane8.setBackground(slidpane);
        btpane9.setBackground(slidpane);
        btpane10.setBackground(slidpane);
        
        btn6.setBackground(btnclick);
        btn2.setBackground(slidpane);
        btn3.setBackground(slidpane);
        btn4.setBackground(slidpane);
        btn5.setBackground(slidpane);
        btn1.setBackground(slidpane);
        btn7.setBackground(slidpane);
        btn8.setBackground(slidpane);
        btn9.setBackground(slidpane);
        btn10.setBackground(slidpane);
    }//GEN-LAST:event_btn6MousePressed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
       Setting st = new Setting();
       jDesktopPane1.removeAll();
       jDesktopPane1.add(st).setVisible(true);
      
    }//GEN-LAST:event_btn6MouseClicked

    private void btnhideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhideMouseClicked
    // Color cr=new Color(23,35,51);
    //           menuss.setBackground(cr);
        menuss.setPreferredSize( new Dimension(180, 560) );
         menuss.revalidate();
               // menu.pack();
                menuss.repaint();
                menuss.setVisible(true);
                btnhide.hide();
                btnshow.setVisible(true);
    }//GEN-LAST:event_btnhideMouseClicked

    private void btnshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshowMouseClicked
      
        int mn = menuss.getWidth();
        if(mn < 300)
        {
           // Color crs= new Color(23, 35, 51);
          //  menuss.setBackground( crs );
            menuss.setPreferredSize( new Dimension(50, 560) );
            menuss.revalidate();
            // menu.pack();
            menuss.repaint();
            menuss.setVisible(true);
            btnhide.setVisible(true);
            btnshow.hide();

        }
        
    }//GEN-LAST:event_btnshowMouseClicked

    private void btn7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseDragged

    private void btn7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseMoved

    private void btn7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn7FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7FocusGained

    private void btn7MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_btn7MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseWheelMoved

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
      Backup bk= new Backup();
      jDesktopPane1.removeAll();
      jDesktopPane1.add(bk).setVisible(true);
    }//GEN-LAST:event_btn7MouseClicked

    private void btn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseEntered

    private void btn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MousePressed
       
        btpane7.setBackground(slidmark);
        btpane2.setBackground(slidpane);
        btpane3.setBackground(slidpane);
        btpane4.setBackground(slidpane);
        btpane1.setBackground(slidpane);
        btpane6.setBackground(slidpane);
        btpane5.setBackground(slidpane);
        btpane8.setBackground(slidpane);
        btpane9.setBackground(slidpane);
        btpane10.setBackground(slidpane);
        
        btn7.setBackground(btnclick);
        btn2.setBackground(slidpane);
        btn3.setBackground(slidpane);
        btn1.setBackground(slidpane);
        btn5.setBackground(slidpane);
        btn6.setBackground(slidpane);
        btn4.setBackground(slidpane);
        btn8.setBackground(slidpane);
        btn9.setBackground(slidpane);
        btn10.setBackground(slidpane);
    }//GEN-LAST:event_btn7MousePressed

    private void btn8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseDragged

    private void btn8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseMoved

    private void btn8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn8FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8FocusGained

    private void btn8MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_btn8MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseWheelMoved

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        Badorder bd= new Badorder();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(bd).setVisible(true);
    }//GEN-LAST:event_btn8MouseClicked

    private void btn8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseEntered

    private void btn8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MousePressed
       
        btpane8.setBackground(slidmark);
        btpane2.setBackground(slidpane);
        btpane3.setBackground(slidpane);
        btpane4.setBackground(slidpane);
        btpane1.setBackground(slidpane);
        btpane6.setBackground(slidpane);
        btpane5.setBackground(slidpane);
        btpane7.setBackground(slidpane);
        btpane9.setBackground(slidpane);
        btpane10.setBackground(slidpane);
        
        btn8.setBackground(btnclick);
        btn2.setBackground(slidpane);
        btn3.setBackground(slidpane);
        btn1.setBackground(slidpane);
        btn5.setBackground(slidpane);
        btn6.setBackground(slidpane);
        btn4.setBackground(slidpane);
        btn7.setBackground(slidpane);
        btn9.setBackground(slidpane);
        btn10.setBackground(slidpane);
    }//GEN-LAST:event_btn8MousePressed

    private void btn10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10MouseDragged

    private void btn10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10MouseMoved

    private void btn10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn10FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10FocusGained

    private void btn10MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_btn10MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10MouseWheelMoved

    private void btn10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MouseClicked
       ReAddStock bd= new ReAddStock();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(bd).setVisible(true);
    }//GEN-LAST:event_btn10MouseClicked

    private void btn10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10MouseEntered

    private void btn10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MousePressed
        
        btpane10.setBackground(slidmark);
        btpane2.setBackground(slidpane);
        btpane3.setBackground(slidpane);
        btpane4.setBackground(slidpane);
        btpane1.setBackground(slidpane);
        btpane6.setBackground(slidpane);
        btpane5.setBackground(slidpane);
        btpane7.setBackground(slidpane);
        btpane8.setBackground(slidpane);
        btpane9.setBackground(slidpane);
        
        btn10.setBackground(btnclick);
        btn2.setBackground(slidpane);
        btn3.setBackground(slidpane);
        btn1.setBackground(slidpane);
        btn5.setBackground(slidpane);
        btn6.setBackground(slidpane);
        btn4.setBackground(slidpane);
        btn7.setBackground(slidpane);
        btn8.setBackground(slidpane);
        btn9.setBackground(slidpane);
    }//GEN-LAST:event_btn10MousePressed

    private void btn9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseDragged

    private void btn9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseMoved

    private void btn9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn9FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9FocusGained

    private void btn9MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_btn9MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseWheelMoved

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
      saleReturn bd= new saleReturn();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(bd).setVisible(true);
    }//GEN-LAST:event_btn9MouseClicked

    private void btn9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseEntered

    private void btn9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MousePressed
        
        btpane9.setBackground(slidmark);
        btpane2.setBackground(slidpane);
        btpane3.setBackground(slidpane);
        btpane4.setBackground(slidpane);
        btpane1.setBackground(slidpane);
        btpane6.setBackground(slidpane);
        btpane5.setBackground(slidpane);
        btpane7.setBackground(slidpane);
        btpane8.setBackground(slidpane);
        btpane10.setBackground(slidpane);
        
        btn9.setBackground(btnclick);
        btn2.setBackground(slidpane);
        btn3.setBackground(slidpane);
        btn1.setBackground(slidpane);
        btn5.setBackground(slidpane);
        btn6.setBackground(slidpane);
        btn4.setBackground(slidpane);
        btn7.setBackground(slidpane);
        btn8.setBackground(slidpane);
        btn10.setBackground(slidpane);
    }//GEN-LAST:event_btn9MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn1;
    private javax.swing.JPanel btn10;
    private javax.swing.JPanel btn2;
    private javax.swing.JPanel btn3;
    private javax.swing.JPanel btn4;
    private javax.swing.JPanel btn5;
    private javax.swing.JPanel btn6;
    private javax.swing.JPanel btn7;
    private javax.swing.JPanel btn8;
    private javax.swing.JPanel btn9;
    private javax.swing.JLabel btnhide;
    private javax.swing.JLabel btnshow;
    private javax.swing.JPanel btpane1;
    private javax.swing.JPanel btpane10;
    private javax.swing.JPanel btpane2;
    private javax.swing.JPanel btpane3;
    private javax.swing.JPanel btpane4;
    private javax.swing.JPanel btpane5;
    private javax.swing.JPanel btpane6;
    private javax.swing.JPanel btpane7;
    private javax.swing.JPanel btpane8;
    private javax.swing.JPanel btpane9;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel imgp1;
    private javax.swing.JLabel imgp2;
    private javax.swing.JLabel imgp3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel lbluname;
    private javax.swing.JPanel menuss;
    // End of variables declaration//GEN-END:variables
}
