/*
/*
      **********Author***********
*************Ruwan Kumara**************

*/
 
package Main;
import java.lang.*;
//import static inter.Home.getDate;
//import static inter.Home.getTime;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
//import org.exolab.castor.types.Date;

/**
 *
 * @author Ruwan
 */
public class login extends javax.swing.JFrame {

     Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    public static String uname;    
    public static String com_name;
    public static String sub_title;
    public static String ex_date;
    public static String dev_name;
    public static String bill_heder;
    public static String con_num;
    public static String email;
    public static String adress;
    String date;
    int valiDate;
    int x,y;
    
    
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        conn=DBConnect.connect();
        develop(); 
        txtusername.setFocusable(true);  
        
        
         Calendar expireDate = Calendar.getInstance();
         
                   // January is 0 (y, m, d)
                   expireDate.set(2025, 9, 26);
                   // Get current date and compare
                   if (Calendar.getInstance().after(expireDate)) {
                     // Die
                     JOptionPane.showMessageDialog(rootPane, "Sorry Your Froduct Is Expired");
                     System.exit(0);
                     
                   }
        
        
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        chkboxspwd = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtpsw = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad\\Downloads\\z.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(193, 222, 136));
        jPanel1.setLayout(null);

        txtusername.setBackground(new java.awt.Color(177, 222, 177));
        txtusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusername.setBorder(null);
        txtusername.setName(""); // NOI18N
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtusername);
        txtusername.setBounds(110, 80, 320, 30);
        txtusername.getAccessibleContext().setAccessibleName("");
        txtusername.getAccessibleContext().setAccessibleDescription("");

        chkboxspwd.setBackground(new java.awt.Color(255, 0, 51));
        chkboxspwd.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        chkboxspwd.setForeground(new java.awt.Color(255, 255, 255));
        chkboxspwd.setText("Show password");
        chkboxspwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxspwdActionPerformed(evt);
            }
        });
        jPanel1.add(chkboxspwd);
        chkboxspwd.setBounds(290, 210, 140, 20);

        jPanel3.setBackground(new java.awt.Color(124, 25, 83));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(100, 110, 330, 3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 60, 120, 20);

        txtpsw.setBackground(new java.awt.Color(177, 222, 177));
        txtpsw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpsw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpsw.setBorder(null);
        jPanel1.add(txtpsw);
        txtpsw.setBounds(110, 160, 320, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 140, 200, 20);

        jPanel4.setBackground(new java.awt.Color(124, 25, 83));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(100, 190, 330, 3);

        jPanel5.setBackground(new java.awt.Color(177, 222, 177));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(90, 250, 330, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 27, 520, 400));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_25px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(495, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        public void clock()
        {
        Thread clock=new Thread()
                {
                public void run()
                {
                    try {
                    while(true)    // for(; ;)
                        {                                                  
                            Calendar cal=new GregorianCalendar();
                            int day=cal.get(Calendar.DAY_OF_MONTH);
                            int month=cal.get(Calendar.MONTH)+1;
                            int year=cal.get(Calendar.YEAR);

                            int second=cal.get(Calendar.SECOND);
                            int minute=cal.get(Calendar.MINUTE);
                            int hour=cal.get(Calendar.HOUR);

                            String time=( hour +":"+ minute +":"+ second);
                            date=( year +"-"+ month +"-"+ day );    
                                sleep(1000);
                        }
                    } catch (InterruptedException ex) {
                       // Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                
                
                };
        clock.start();
 
    }

    
    private void develop()
    {
        String un=login.uname;
         try {
             String sql="SELECT * FROM `developer`";
           // String q="SELECT returndate FROM borrowdetails where mid='"+ name +"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           while(rs.next())
           {
              
                com_name=rs.getString("company_name");
                sub_title=rs.getString("sub_title");
                ex_date=rs.getString("ex_date");
                dev_name=rs.getString("deve_name");
                bill_heder=rs.getString("bill_heder");
                con_num=rs.getString("contac_no");
                email=rs.getString("email");
                adress=rs.getString("adress");
             // JOptionPane.showMessageDialog(rootPane, sub_title);
              
           }
           
                            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    
    
    
    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void chkboxspwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxspwdActionPerformed
        if(chkboxspwd.isSelected())
        {
            txtpsw.setEchoChar((char)0);
        }
        else
        {
            txtpsw.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxspwdActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
       
        
         Calendar expireDate = Calendar.getInstance();
         
                   // January is 0 (y, m, d)
                   expireDate.set(2025, 9, 25);
                   // Get current date and compare
                   if (Calendar.getInstance().after(expireDate)) {
                     // Die
                     JOptionPane.showMessageDialog(rootPane, "Sorry Your Froduct Is Expired");
                     System.exit(0);
                     
                   }
                   
                   else
                   {
        
              
                                uname=txtusername.getText();
                                String pword=txtpsw.getText();

                                try {

                                    String sq="SELECT password FROM admin WHERE user_name='"+uname+"' ";

                                    pst=conn.prepareStatement(sq);
                                    rs=pst.executeQuery();
                                    if(rs.next()){

                                        String psw=rs.getString("password");

                                        if(psw.equals(pword))
                                    {
                                       Home ho=new Home();
                                       ho.setVisible(true); 
                                       this.dispose();
                                       uname = txtusername.getText();
                                    }
                                    else
                                    {
                                       JOptionPane.showMessageDialog(rootPane, "Username or Password Incorrect"); 
                                       txtusername.setText("");
                                       txtpsw.setText("");
                                    }
                                    }
                                    else
                                    {
                                    JOptionPane.showMessageDialog(rootPane, "username incorrect");
                                    txtusername.setText("");
                                       txtpsw.setText("");
                                    }

                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(rootPane, e); 
                                }
                   }
        
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
         x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
       int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkboxspwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField txtpsw;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

   

    
}
