/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.lang.*;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.print.Book.*;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
// bar code block  import net.connectcode.Code128Auto;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ruwan
 */
public class recieved extends javax.swing.JInternalFrame {

    /**
     * Creates new form recieved
     */
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    private String parseSql;
    
    
    
    public recieved() {
         initComponents();  
         conn=DBConnect.connect();
         autoId();
         tablelord();
         panelord();
         loDisable();
        
         
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
         
        
    }

    private void  theader()
    {
    JTableHeader thead = tableitemlist.getTableHeader();
       thead.setForeground(Color.BLUE);
    
       thead.setFont(new Font("Tahome", Font.BOLD, 14));
       
        TableColumn col1=tableitemlist.getColumnModel().getColumn(0);
        col1.setPreferredWidth(100);
        TableColumn col2=tableitemlist.getColumnModel().getColumn(1);
        col2.setPreferredWidth(110);
        TableColumn col3=tableitemlist.getColumnModel().getColumn(2);
        col3.setPreferredWidth(85);
        TableColumn col4=tableitemlist.getColumnModel().getColumn(3);
        col4.setPreferredWidth(100);
        TableColumn col5=tableitemlist.getColumnModel().getColumn(4);
        col5.setPreferredWidth(105);
        TableColumn col6=tableitemlist.getColumnModel().getColumn(5);
        col6.setPreferredWidth(95);
        TableColumn col7=tableitemlist.getColumnModel().getColumn(6);
        col7.setPreferredWidth(110);
        TableColumn col8=tableitemlist.getColumnModel().getColumn(7);
        col8.setPreferredWidth(115);
         TableColumn col9=tableitemlist.getColumnModel().getColumn(8);
        col9.setPreferredWidth(115);
         TableColumn col10=tableitemlist.getColumnModel().getColumn(9);
        col10.setPreferredWidth(110);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtreno = new javax.swing.JTextField();
        txtitemno = new javax.swing.JTextField();
        txtitemname = new javax.swing.JTextField();
        txtdescription = new javax.swing.JTextField();
        txtquentity = new javax.swing.JTextField();
        txtbuyprice = new javax.swing.JTextField();
        txtsellprice = new javax.swing.JTextField();
        txttotalprice = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnupdate = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnsave = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbsearch = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        btnselect = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btndelete = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnclear = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnaddstock = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnprint = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableitemlist = new javax.swing.JTable();
        lblbarcode = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        datereceive = new com.toedter.calendar.JDateChooser();
        dateexpire = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(880, 510));
        setMinimumSize(new java.awt.Dimension(880, 510));
        setPreferredSize(new java.awt.Dimension(880, 510));

        jPanel1.setBackground(new java.awt.Color(251, 252, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel1.setText("Receving No");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 100, 100, 23);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel2.setText("Receving Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 140, 100, 23);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel4.setText("Item No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 170, 67, 23);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel3.setText("Item Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 200, 90, 23);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel5.setText("Description");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 230, 78, 23);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel7.setText("Quantity");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 300, 67, 23);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel6.setText("Ex Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 270, 67, 23);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel8.setText("Buying Price");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 330, 90, 23);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel9.setText("Selling Price");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 360, 90, 20);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel10.setText("Total Price");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 390, 90, 23);

        txtreno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtreno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrenoActionPerformed(evt);
            }
        });
        jPanel1.add(txtreno);
        txtreno.setBounds(120, 100, 170, 27);

        txtitemno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtitemno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemnoActionPerformed(evt);
            }
        });
        txtitemno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtitemnoKeyReleased(evt);
            }
        });
        jPanel1.add(txtitemno);
        txtitemno.setBounds(120, 170, 170, 27);

        txtitemname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtitemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtitemname);
        txtitemname.setBounds(120, 200, 170, 27);

        txtdescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtdescription);
        txtdescription.setBounds(120, 230, 170, 27);

        txtquentity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtquentity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquentityActionPerformed(evt);
            }
        });
        txtquentity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtquentityKeyTyped(evt);
            }
        });
        jPanel1.add(txtquentity);
        txtquentity.setBounds(120, 300, 170, 27);

        txtbuyprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtbuyprice.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtbuypriceComponentAdded(evt);
            }
        });
        txtbuyprice.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtbuypriceAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtbuyprice.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtbuypriceCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtbuypriceInputMethodTextChanged(evt);
            }
        });
        txtbuyprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuypriceActionPerformed(evt);
            }
        });
        txtbuyprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuypriceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuypriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuypriceKeyTyped(evt);
            }
        });
        jPanel1.add(txtbuyprice);
        txtbuyprice.setBounds(120, 330, 170, 27);

        txtsellprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsellprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsellpriceActionPerformed(evt);
            }
        });
        txtsellprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsellpriceKeyTyped(evt);
            }
        });
        jPanel1.add(txtsellprice);
        txtsellprice.setBounds(120, 360, 170, 27);

        txttotalprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttotalprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalpriceActionPerformed(evt);
            }
        });
        txttotalprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttotalpriceKeyTyped(evt);
            }
        });
        jPanel1.add(txttotalprice);
        txttotalprice.setBounds(120, 390, 170, 30);

        jPanel2.setLayout(new java.awt.CardLayout());

        btnupdate.setBackground(new java.awt.Color(193, 222, 136));
        btnupdate.setPreferredSize(new java.awt.Dimension(100, 40));
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });
        btnupdate.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rotate-24.png"))); // NOI18N
        jLabel19.setText("Update");
        btnupdate.add(jLabel19);
        jLabel19.setBounds(10, 4, 90, 30);

        jPanel2.add(btnupdate, "card3");

        btnsave.setBackground(new java.awt.Color(46, 149, 152));
        btnsave.setPreferredSize(new java.awt.Dimension(100, 40));
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
        });
        btnsave.setLayout(null);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/upload-24.png"))); // NOI18N
        jLabel20.setText("Save");
        btnsave.add(jLabel20);
        jLabel20.setBounds(20, 10, 70, 24);

        jPanel2.add(btnsave, "card4");

        jPanel1.add(jPanel2);
        jPanel2.setBounds(170, 430, 100, 40);

        jPanel5.setBackground(new java.awt.Color(193, 222, 136));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Item Details");

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Search By");

        cmbsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Tittle", "receive_no", "item_number", "item_name" }));

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cmbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel11))
                    .addComponent(cmbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 10, 850, 50);

        btnselect.setBackground(new java.awt.Color(193, 222, 136));
        btnselect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnselect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnselectMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/star-7-32.png"))); // NOI18N
        jLabel12.setText("Select");

        javax.swing.GroupLayout btnselectLayout = new javax.swing.GroupLayout(btnselect);
        btnselect.setLayout(btnselectLayout);
        btnselectLayout.setHorizontalGroup(
            btnselectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnselectLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        btnselectLayout.setVerticalGroup(
            btnselectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(btnselect);
        btnselect.setBounds(320, 420, 90, 40);

        btndelete.setBackground(new java.awt.Color(193, 222, 136));
        btndelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-24.png"))); // NOI18N
        jLabel13.setText("delete");

        javax.swing.GroupLayout btndeleteLayout = new javax.swing.GroupLayout(btndelete);
        btndelete.setLayout(btndeleteLayout);
        btndeleteLayout.setHorizontalGroup(
            btndeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btndeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        btndeleteLayout.setVerticalGroup(
            btndeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(btndelete);
        btndelete.setBounds(420, 420, 90, 40);

        btnclear.setBackground(new java.awt.Color(193, 222, 136));
        btnclear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclearMouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(193, 222, 136));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/brush-24.png"))); // NOI18N
        jLabel15.setText("clear");

        javax.swing.GroupLayout btnclearLayout = new javax.swing.GroupLayout(btnclear);
        btnclear.setLayout(btnclearLayout);
        btnclearLayout.setHorizontalGroup(
            btnclearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnclearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        btnclearLayout.setVerticalGroup(
            btnclearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(btnclear);
        btnclear.setBounds(520, 420, 80, 40);

        btnaddstock.setBackground(new java.awt.Color(193, 222, 136));
        btnaddstock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnaddstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddstockMouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-image-24.png"))); // NOI18N
        jLabel23.setText("add to stock");

        javax.swing.GroupLayout btnaddstockLayout = new javax.swing.GroupLayout(btnaddstock);
        btnaddstock.setLayout(btnaddstockLayout);
        btnaddstockLayout.setHorizontalGroup(
            btnaddstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnaddstockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(33, 33, 33))
        );
        btnaddstockLayout.setVerticalGroup(
            btnaddstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnaddstockLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(btnaddstock);
        btnaddstock.setBounds(710, 420, 130, 40);

        btnprint.setBackground(new java.awt.Color(193, 222, 136));
        btnprint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprintMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer-24.png"))); // NOI18N
        jLabel22.setText("print");

        javax.swing.GroupLayout btnprintLayout = new javax.swing.GroupLayout(btnprint);
        btnprint.setLayout(btnprintLayout);
        btnprintLayout.setHorizontalGroup(
            btnprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnprintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnprintLayout.setVerticalGroup(
            btnprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(btnprint);
        btnprint.setBounds(610, 420, 90, 40);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableitemlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableitemlist.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableitemlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableitemlistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableitemlist);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(310, 80, 530, 290);

        lblbarcode.setEditable(false);
        lblbarcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(lblbarcode);
        lblbarcode.setBounds(20, 430, 110, 45);

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, 70, 550, 310);

        jLabel17.setFont(new java.awt.Font("Lucida Bright", 3, 14)); // NOI18N
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(310, 390, 550, 90);
        jPanel1.add(datereceive);
        datereceive.setBounds(120, 140, 170, 27);
        jPanel1.add(dateexpire);
        dateexpire.setBounds(120, 270, 170, 27);

        jLabel14.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 60, 290, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttotalpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalpriceActionPerformed

    private void txtsellpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsellpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsellpriceActionPerformed

    private void txtbuypriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuypriceActionPerformed
       
    }//GEN-LAST:event_txtbuypriceActionPerformed

    private void txtrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrenoActionPerformed

    private void txtitemnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemnoActionPerformed
      
    }//GEN-LAST:event_txtitemnoActionPerformed

    private void txtquentityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquentityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquentityActionPerformed

    private void txtitemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitemnameActionPerformed

    private void receiveStocksearch()
    {
        String tit=cmbsearch.getSelectedItem().toString();
        
       try {
            if(tit=="receive_no")
            {
             
             parseSql="SELECT receivestock.receive_no as 'RECEIVE NO', receivestock.receive_date as 'RECEIVE DATE', receivestock.item_number as 'ITEM NO', receivestock.item_name as 'ITEM NAME', receivestock.description as 'DESCRIPTION', receivestock.quentity as 'QUANTITY', receivestock.expire_date as 'EXPRIER DATE', receivestock.buying_price as 'BUYING PRICE', receivestock.selling_price as 'SELLING PRICE', receivestock.total_price as 'TOTAL PRICE' FROM receivestock where receive_no Like'%"+txtsearch.getText()+"%' and mark='1'";
            pst=conn.prepareStatement(parseSql);
            rs=pst.executeQuery();
            tableitemlist.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }
            else if(tit=="item_number")
            {
             parseSql="SELECT receivestock.receive_no as 'RECEIVE NO', receivestock.receive_date as 'RECEIVE DATE', receivestock.item_number as 'ITEM NO', receivestock.item_name as 'ITEM NAME', receivestock.description as 'DESCRIPTION', receivestock.quentity as 'QUANTITY', receivestock.expire_date as 'EXPRIER DATE', receivestock.buying_price as 'BUYING PRICE', receivestock.selling_price as 'SELLING PRICE', receivestock.total_price as 'TOTAL PRICE' FROM receivestock where item_number LIKE'%"+txtsearch.getText()+"%' and mark='1'";
            pst=conn.prepareStatement(parseSql);
            rs=pst.executeQuery();
            tableitemlist.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }
            else if(tit=="item_name")
            {
             
              parseSql="SELECT receivestock.receive_no as 'RECEIVE NO', receivestock.receive_date as 'RECEIVE DATE', receivestock.item_number as 'ITEM NO', receivestock.item_name as 'ITEM NAME', receivestock.description as 'DESCRIPTION', receivestock.quentity as 'QUANTITY', receivestock.expire_date as 'EXPRIER DATE', receivestock.buying_price as 'BUYING PRICE', receivestock.selling_price as 'SELLING PRICE', receivestock.total_price as 'TOTAL PRICE' FROM receivestock where item_name Like'%"+txtsearch.getText()+"%' and mark='1'";
            pst=conn.prepareStatement(parseSql);
            rs=pst.executeQuery();
            tableitemlist.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "Please select tittle for Search");
            }
            
        } catch (Exception e) {
        } 
    }
    
    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void panelord()
    {
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(btnsave);
        jPanel2.repaint();
        jPanel2.revalidate();
    
    }
    
    
     private void autoId()
    {
        try {
             String sql="SELECT receive_no FROM receivestock ORDER BY receive_no DESC LIMIT 1";
           // String q="SELECT returndate FROM borrowdetails where mid='"+ name +"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next())
           {
                String rnno=rs.getString("receive_no");
                int co=rnno.length();
               String txt= rnno.substring(0, 2);
               String num=rnno.substring(2, co);
               int n=Integer.parseInt(num);
               n++;
               String snum=Integer.toString(n);
               String ftxt=txt+snum;
               txtreno.setText(ftxt);
            
           }
           else
           {
               txtreno.setText("RN1000");
           }
           
                            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
       
    }
     
      private void tablelord()
    {
        try {
            String sql="SELECT receivestock.receive_no as 'RECEIVE NO', receivestock.receive_date as 'RECEIVE DATE', receivestock.item_number as 'ITEM NO', receivestock.item_name as 'ITEM NAME', receivestock.description as 'DESCRIPTION', receivestock.quentity as 'QUANTITY', receivestock.expire_date as 'EXPRIER DATE', receivestock.buying_price as 'BUYING PRICE', receivestock.selling_price as 'SELLING PRICE', receivestock.total_price as 'TOTAL PRICE' FROM receivestock where mark='"+1+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tableitemlist.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
       theader();
    }
      private void clearField()
      {
         // txtreno.setText("");
         ((JTextField)datereceive.getDateEditor().getUiComponent()).setText("");
         txtitemno.setText("");
         txtitemname.setText("");
         txtdescription.setText("");
         txtquentity.setText("");
         ((JTextField)dateexpire.getDateEditor().getUiComponent()).setText("");
         txtbuyprice.setText("");
         txtsellprice.setText("");
         txttotalprice.setText("");
         txtsearch.setText("");
      }
    
    
    private void txtbuypriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuypriceKeyReleased
       
        double pri=Integer.parseInt(txtbuyprice.getText());
        double que=Integer.parseInt(txtquentity.getText());
        double tpri=pri*que;
        txttotalprice.setText(String.valueOf(tpri));      
    }//GEN-LAST:event_txtbuypriceKeyReleased

    private void txtbuypriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuypriceKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)&& !evt.isAltDown())
        {
        evt.consume();
        }
        btnsave.setEnabled(true);
    }//GEN-LAST:event_txtbuypriceKeyTyped

    private void txtbuypriceInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtbuypriceInputMethodTextChanged
        
    }//GEN-LAST:event_txtbuypriceInputMethodTextChanged

    private void txtbuypriceAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtbuypriceAncestorAdded
        
    }//GEN-LAST:event_txtbuypriceAncestorAdded

    private void txtbuypriceComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtbuypriceComponentAdded
        
    }//GEN-LAST:event_txtbuypriceComponentAdded

    private void txtbuypriceCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtbuypriceCaretPositionChanged
        
    }//GEN-LAST:event_txtbuypriceCaretPositionChanged

    private void txtbuypriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuypriceKeyPressed
        
    }//GEN-LAST:event_txtbuypriceKeyPressed

    private void allReceive()
    {
    try {
             JasperDesign jasdi=JRXmlLoader.load("C:\\Users\\ccs\\Documents\\NetBeansProjects\\Inventory\\src\\report\\ReceiveStock.jrxml");
            String sql="SELECT receivestock.receive_no as 'RECEIVE NO', receivestock.receive_date as 'RECEIVE DATE', receivestock.item_number as 'ITEM NO', receivestock.item_name as 'ITEM NAME', receivestock.description as 'DESCRIPTION', receivestock.quentity as 'QUANTITY', receivestock.expire_date as 'EXPRIER DATE', receivestock.buying_price as 'BUYING PRICE', receivestock.selling_price as 'SELLING PRICE', receivestock.total_price as 'TOTAL PRICE' FROM receivestock where mark='"+1+"'";
            JRDesignQuery newQuery=new JRDesignQuery();
            newQuery.setText(sql);
            jasdi.setQuery(newQuery);
            
            
              
              JasperReport js=JasperCompileManager.compileReport(jasdi);
             JasperPrint jp=JasperFillManager.fillReport(js,null,conn);
            // JasperExportManager.exportReportToHtmlFile(jp ,ore);
             JasperViewer.viewReport(jp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void filterReceive()
    {
     try {
             JasperDesign jasdi=JRXmlLoader.load("C:\\Users\\ccs\\Documents\\NetBeansProjects\\Inventory\\src\\report\\ReceiveStock.jrxml");
           // String sql="SELECT receivestock.receive_no as 'RECEIVE NO', receivestock.receive_date as 'RECEIVE DATE', receivestock.item_number as 'ITEM NO', receivestock.item_name as 'ITEM NAME', receivestock.description as 'DESCRIPTION', receivestock.quentity as 'QUANTITY', receivestock.expire_date as 'EXPRIER DATE', receivestock.buying_price as 'BUYING PRICE', receivestock.selling_price as 'SELLING PRICE', receivestock.total_price as 'TOTAL PRICE' FROM receivestock where item_number LIKE'%"+txtsearch.getText()+"%' and mark='1'";
           
            JRDesignQuery newQuery=new JRDesignQuery();
            newQuery.setText(parseSql);
            jasdi.setQuery(newQuery);
            
            
              
              JasperReport js=JasperCompileManager.compileReport(jasdi);
             JasperPrint jp=JasperFillManager.fillReport(js,null,conn);
            // JasperExportManager.exportReportToHtmlFile(jp ,ore);
             JasperViewer.viewReport(jp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    
    private void seDeAddDisable()
    {
     btnaddstock.setEnabled(false);
         btndelete.setEnabled(false);
         btnselect.setEnabled(false);
         btnaddstock.setEnabled(false);
    }
    
    private void txtquentityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquentityKeyTyped
        
        char c=evt.getKeyChar();
        if(Character.isLetter(c)&& !evt.isAltDown())
        {
        evt.consume();
        }
        
    }//GEN-LAST:event_txtquentityKeyTyped

    private void txtsellpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsellpriceKeyTyped
       char c=evt.getKeyChar();
        if(Character.isLetter(c)&& !evt.isAltDown())
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtsellpriceKeyTyped

    private void txttotalpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalpriceKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)&& !evt.isAltDown())
        {
        evt.consume();
        }
    }//GEN-LAST:event_txttotalpriceKeyTyped

    private void delete()
    {
         int x=JOptionPane.showConfirmDialog(rootPane, "Do you realy want to delete");
        if(x==0)
        {
        try {
                String sql="DELETE FROM receivestock where receive_no='"+ txtsearch.getText() +"'";
                pst=conn.prepareStatement(sql);
                pst.execute();
                
                tablelord();
            } catch (Exception e) {
            }
        }
    
    }
    private void markitem()
    {
      try {
              String squpdate = "UPDATE receivestock SET mark=mark -'"+1+"' WHERE receive_no='"+txtsearch.getText()+"'";
              pst=conn.prepareStatement(squpdate);
                pst.execute();  
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,e);              
            }  
    }
    
    
    private void tableitemlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableitemlistMouseClicked
      
        DefaultTableModel tmodel=(DefaultTableModel)tableitemlist.getModel();
        int selectrowindex=tableitemlist.getSelectedRow();
        txtsearch.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        
        btnaddstock.setEnabled(true);
        btndelete.setEnabled(true);
        btnselect.setEnabled(true);
        btnprint.setEnabled(false);
    }//GEN-LAST:event_tableitemlistMouseClicked

    private void datereceiveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datereceiveFocusGained
      
       
    }//GEN-LAST:event_datereceiveFocusGained

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
      receiveStocksearch();
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtitemnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemnoKeyReleased
       barcode();
    }//GEN-LAST:event_txtitemnoKeyReleased

    private void btnselectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselectMouseClicked
      
        try {
            String sq="SELECT `receive_no`, `receive_date`, `item_number`, `item_name`, `description`, `quentity`, `expire_date`, `buying_price`, `selling_price`, `total_price` FROM `receivestock` WHERE receive_no='"+txtsearch.getText()+"'";
           
            pst=conn.prepareStatement(sq);
            rs=pst.executeQuery();
            while(rs.next()){
                txtreno.setText(rs.getString("receive_no"));
                ((JTextField)datereceive.getDateEditor().getUiComponent()).setText(rs.getString("receive_date"));
                txtitemno.setText(rs.getString("item_number"));
                txtitemname.setText(rs.getString("item_name"));
                txtdescription.setText(rs.getString("description"));
                txtquentity.setText(rs.getString("quentity"));
                ((JTextField)dateexpire.getDateEditor().getUiComponent()).setText(rs.getString("expire_date"));
                txtbuyprice.setText(rs.getString("buying_price"));
                txtsellprice.setText(rs.getString("selling_price"));
                txttotalprice.setText(rs.getString("total_price"));
                
            }
        } catch (Exception e) {
        }
        
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(btnupdate);
        jPanel2.repaint();
        jPanel2.revalidate();
        
        btnupdate.setEnabled(true);
        seDeAddDisable();
        barcode();
        
    }//GEN-LAST:event_btnselectMouseClicked

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
          delete();
       seDeAddDisable();
       btnprint.setEnabled(true);
       clearField();
        
    }//GEN-LAST:event_btndeleteMouseClicked

    private void btnclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseClicked
       tablelord();
        autoId();
        panelord();
        clearField();
        txtsearch.setText("");
        btnprint.setEnabled(true);
        btndelete.setEnabled(false);
        btnselect.setEnabled(false);
        btnaddstock.setEnabled(false);
    }//GEN-LAST:event_btnclearMouseClicked

    private void btnprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintMouseClicked
       if(tableitemlist.getRowCount()<1)
{
     JOptionPane.showMessageDialog(rootPane,"No details to print");
}
   else if(txtsearch.getText().length()>0)
    {
    
    filterReceive();
    }
    else{
    allReceive();
    }
    }//GEN-LAST:event_btnprintMouseClicked

    private void btnaddstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddstockMouseClicked
       DefaultTableModel tmodel=(DefaultTableModel)tableitemlist.getModel();
        int selectrowindex=tableitemlist.getSelectedRow();
        if(selectrowindex>-1)
        {
        txtsearch.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        
        
       String receno=tmodel.getValueAt(selectrowindex, 0).toString();
      // String redate=tmodel.getValueAt(selectrowindex, 1).toString();
       String itemno=tmodel.getValueAt(selectrowindex, 2).toString();
      // String itemna=tmodel.getValueAt(selectrowindex, 3).toString();
     //  String descri=tmodel.getValueAt(selectrowindex, 4).toString();
       String quentity=tmodel.getValueAt(selectrowindex, 5).toString();
      // String exdate=tmodel.getValueAt(selectrowindex, 6).toString();
     //  String buyprice=tmodel.getValueAt(selectrowindex, 7).toString();
     //  String selprice=tmodel.getValueAt(selectrowindex, 8).toString();
      // String totprice=tmodel.getValueAt(selectrowindex, 9).toString();
       
        try {
                String q= "INSERT INTO `stock`(`receive_no`, `item_number`, `quentity`) VALUES ('"+receno+"','"+itemno+"','"+quentity+"')";
                 pst=conn.prepareStatement(q);
                pst.execute(); 
                JOptionPane.showMessageDialog(rootPane,"Item sent successfully");
                
                    } 
                catch (Exception e) 
                {
       
                 JOptionPane.showMessageDialog(rootPane,e);                    
                } 
        seDeAddDisable();
       markitem();
       tablelord();
       btnprint.setEnabled(true);
         clearField();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Please select a item to add");
        }
    }//GEN-LAST:event_btnaddstockMouseClicked

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
       String receno=txtreno.getText();
       String redate=((JTextField)datereceive.getDateEditor().getUiComponent()).getText();
       String itemno=txtitemno.getText();
       String itemna=txtitemname.getText();
       String descri=txtdescription.getText();
       String quentity=txtquentity.getText();
       String exdate=((JTextField)dateexpire.getDateEditor().getUiComponent()).getText();
       String buyprice=txtbuyprice.getText();
       String selprice=txtsellprice.getText();
       String totprice=txttotalprice.getText();
       
        try {
                String q= "INSERT INTO `receivestock`(`receive_no`, `receive_date`, `item_number`, `item_name`, `description`, `quentity`, `expire_date`, `buying_price`, `selling_price`, `total_price`,`mark`) VALUES ('"+receno+"','"+redate+"' ,'"+itemno+"' ,'"+itemna+"' ,'"+descri+"' ,'"+quentity+"' ,'"+exdate+"' ,'"+buyprice+"' ,'"+selprice+"' ,'"+totprice+"','"+1+"')";
                 pst=conn.prepareStatement(q);
                pst.execute(); 
                JOptionPane.showMessageDialog(rootPane,"save success");
                
                    } 
                catch (Exception e) 
                {
       
                 JOptionPane.showMessageDialog(rootPane,e);                    
                }  
             tablelord();   
             autoId(); 
             clearField();
             btnsave.setEnabled(false);
             seDeAddDisable();
             btnprint.setEnabled(true);
            lblbarcode.setText("");
    }//GEN-LAST:event_btnsaveMouseClicked

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
       
          datalord();
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(btnsave);
        jPanel2.repaint();
        jPanel2.revalidate();
        
        clearField();
         autoId();
        seDeAddDisable();
        btnprint.setEnabled(true);
        lblbarcode.setText("");
    }//GEN-LAST:event_btnupdateMouseClicked
private void barcode()
{

 // bar code block  Code128Auto co123=new Code128Auto();
  // bar code block      String bacode=co123.encode(txtitemno.getText());
  // bar code block      lblbarcode.setText(bacode);
  // bar code block      lblbarcode.setFont(new java.awt.Font("CCode128_S3_Trial", java.awt.Font.PLAIN, 24));
}


private void datalord()
{

    String receno=txtreno.getText();
       String redate=((JTextField)datereceive.getDateEditor().getUiComponent()).getText();
       String itemno=txtitemno.getText();
       String itemna=txtitemname.getText();
       String descri=txtdescription.getText();
       String quentity=txtquentity.getText();
       String exdate=((JTextField)dateexpire.getDateEditor().getUiComponent()).getText();
       String buyprice=txtbuyprice.getText();
       String selprice=txtsellprice.getText();
       String totprice=txttotalprice.getText();
        
         int x=JOptionPane.showConfirmDialog(rootPane, "Do you realy want to update");
        if(x==0)
        {
        try {
              String squpdate = "UPDATE `receivestock` SET `receive_no`='"+receno+"',`receive_date`='"+redate+"',`item_number`='"+itemno+"',`item_name`='"+itemna+"',`description`='"+descri+"',`quentity`='"+quentity+"',`expire_date`='"+exdate+"',`buying_price`='"+buyprice+"',`selling_price`='"+selprice+"',`total_price`='"+totprice+"' WHERE receive_no='"+txtsearch.getText()+"'";
              pst=conn.prepareStatement(squpdate);
                pst.execute();  
                tablelord();
            } catch (Exception e) {
            }
        }

}
    
private void loDisable()
{
    btnsave.setEnabled(false);
    btnupdate.setEnabled(false);
    btnselect.setEnabled(false);
    btndelete.setEnabled(false);
   // btnclear.setEnabled(false);
    btnaddstock.setEnabled(false);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnaddstock;
    private javax.swing.JPanel btnclear;
    private javax.swing.JPanel btndelete;
    private javax.swing.JPanel btnprint;
    private javax.swing.JPanel btnsave;
    private javax.swing.JPanel btnselect;
    private javax.swing.JPanel btnupdate;
    private javax.swing.JComboBox<String> cmbsearch;
    private com.toedter.calendar.JDateChooser dateexpire;
    private com.toedter.calendar.JDateChooser datereceive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lblbarcode;
    private javax.swing.JTable tableitemlist;
    private javax.swing.JTextField txtbuyprice;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtitemname;
    private javax.swing.JTextField txtitemno;
    private javax.swing.JTextField txtquentity;
    private javax.swing.JTextField txtreno;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsellprice;
    private javax.swing.JTextField txttotalprice;
    // End of variables declaration//GEN-END:variables
}
