/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.lang.*;
//import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.awt.Color;
import java.awt.Font;
import java.awt.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;  
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ruwan
 */
public class Report extends javax.swing.JInternalFrame {

    /**
     * Creates new form Report
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    PreparedStatement pst1=null;
    ResultSet rs1=null;
    String sqr1;
    Connection conn1;
    Object[] column={"Business_Date","Total_Sale","Transaction","Net_Income"};
    DefaultTableModel dTM=new DefaultTableModel();
    Object[] row=new Object[4];
    private String reportSql;
    private int selectrow;
    Double saleReturn;
    Double reCost;
    
    
    public Report() {
        initComponents();
        conn=DBConnect.connect();
        conn1=DBConnect.connect();
        saleLord();
        lordBtnDissable();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsale = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblprintDetails = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fromDate = new com.toedter.calendar.JDateChooser();
        toDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtsalesum = new javax.swing.JTextField();
        txtincome = new javax.swing.JTextField();
        txttransaction = new javax.swing.JTextField();
        btnsave = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnclear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btndelet = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnprint = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(880, 510));
        setPreferredSize(new java.awt.Dimension(880, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(880, 510));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sale Report");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 30, 180, 31);

        tblsale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblsale);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 110, 350, 160);

        tblprintDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblprintDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblprintDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblprintDetails);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(440, 110, 390, 160);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel7.setText("Sales Valuat");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 90, 130, 20);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel8.setText("Daily Sales");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 90, 120, 20);

        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel11.setText("From");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(90, 320, 50, 21);

        fromDate.setDateFormatString("yyyy-MM-dd");
        fromDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fromDatePropertyChange(evt);
            }
        });
        jPanel1.add(fromDate);
        fromDate.setBounds(150, 320, 180, 30);

        toDate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(toDate);
        toDate.setBounds(370, 320, 180, 30);

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel12.setText("To");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(340, 320, 20, 21);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel10.setText("Select Date");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 300, 110, 20);

        jButton6.setBackground(new java.awt.Color(193, 222, 136));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-12-24.png"))); // NOI18N
        jLabel18.setText("Search");

        javax.swing.GroupLayout jButton6Layout = new javax.swing.GroupLayout(jButton6);
        jButton6.setLayout(jButton6Layout);
        jButton6Layout.setHorizontalGroup(
            jButton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jButton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jButton6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jButton6Layout.setVerticalGroup(
            jButton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jButton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jButton6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jButton6);
        jButton6.setBounds(560, 320, 90, 30);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 290, 600, 70);

        jLabel14.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel14.setText("Total Sales");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(80, 390, 100, 21);

        jLabel15.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel15.setText("Net Incomes");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(80, 420, 97, 21);

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel16.setText("Transactions");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(370, 390, 102, 21);

        txtsalesum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsalesum.setText("0.0");
        txtsalesum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalesumActionPerformed(evt);
            }
        });
        jPanel1.add(txtsalesum);
        txtsalesum.setBounds(200, 380, 150, 30);

        txtincome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtincome.setText("0.0");
        txtincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtincomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtincome);
        txtincome.setBounds(200, 420, 150, 30);

        txttransaction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttransaction.setText("0");
        jPanel1.add(txttransaction);
        txttransaction.setBounds(480, 380, 160, 30);

        btnsave.setBackground(new java.awt.Color(193, 222, 136));
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/upload-24.png"))); // NOI18N
        jLabel4.setText("Save");

        javax.swing.GroupLayout btnsaveLayout = new javax.swing.GroupLayout(btnsave);
        btnsave.setLayout(btnsaveLayout);
        btnsaveLayout.setHorizontalGroup(
            btnsaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btnsaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnsaveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnsaveLayout.setVerticalGroup(
            btnsaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnsaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnsaveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnsave);
        btnsave.setBounds(400, 420, 90, 30);

        btnclear.setBackground(new java.awt.Color(193, 222, 136));
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclearMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/brush-24.png"))); // NOI18N
        jLabel1.setText("Clear");

        javax.swing.GroupLayout btnclearLayout = new javax.swing.GroupLayout(btnclear);
        btnclear.setLayout(btnclearLayout);
        btnclearLayout.setHorizontalGroup(
            btnclearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btnclearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnclearLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnclearLayout.setVerticalGroup(
            btnclearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnclearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnclearLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnclear);
        btnclear.setBounds(540, 420, 90, 30);

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 370, 600, 90);

        btndelet.setBackground(new java.awt.Color(193, 222, 136));
        btndelet.setPreferredSize(new java.awt.Dimension(90, 40));
        btndelet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeletMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-24.png"))); // NOI18N
        jLabel19.setText("Delete");

        javax.swing.GroupLayout btndeletLayout = new javax.swing.GroupLayout(btndelet);
        btndelet.setLayout(btndeletLayout);
        btndeletLayout.setHorizontalGroup(
            btndeletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btndeletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btndeletLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btndeletLayout.setVerticalGroup(
            btndeletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(btndeletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btndeletLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btndelet);
        btndelet.setBounds(710, 330, 90, 40);

        btnprint.setBackground(new java.awt.Color(193, 222, 136));
        btnprint.setPreferredSize(new java.awt.Dimension(90, 40));
        btnprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprintMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer-24.png"))); // NOI18N
        jLabel20.setText("Print");

        javax.swing.GroupLayout btnprintLayout = new javax.swing.GroupLayout(btnprint);
        btnprint.setLayout(btnprintLayout);
        btnprintLayout.setHorizontalGroup(
            btnprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btnprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnprintLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnprintLayout.setVerticalGroup(
            btnprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(btnprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnprintLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnprint);
        btnprint.setBounds(710, 400, 90, 40);

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(680, 290, 140, 170);

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 280, 770, 190);

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 80, 820, 400);

        jPanel2.setBackground(new java.awt.Color(193, 222, 136));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 820, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fromDatePropertyChange
       
    }//GEN-LAST:event_fromDatePropertyChange
    
    private void txtsalesumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalesumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalesumActionPerformed

    private void txtincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtincomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtincomeActionPerformed

    private void tblprintDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblprintDetailsMouseClicked
        btndelet.setEnabled(true);
    }//GEN-LAST:event_tblprintDetailsMouseClicked

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
        dTM.setColumnIdentifiers(column);
        tblprintDetails.setModel(dTM);
        theader();
        String saleFDate=((JTextField)fromDate.getDateEditor().getUiComponent()).getText();
        String saleTDate=((JTextField)toDate.getDateEditor().getUiComponent()).getText();
        try {
              row[0]=saleFDate+"   "+saleTDate;
              row[1]=txtsalesum.getText();
              row[2]=txttransaction.getText();
              row[3]=txtincome.getText();
              dTM.addRow(row);
        } catch (Exception e) {
        }
         fClear();
         btnprint.setEnabled(true);
         btnsave.setEnabled(false);  
    }//GEN-LAST:event_btnsaveMouseClicked

    private void btnclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseClicked
        fClear();
       btnsave.setEnabled(false);
    }//GEN-LAST:event_btnclearMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
       saleFilter();
       int stv=Integer.parseInt(txttransaction.getText());
       if(stv>0)
       {
       btnsave.setEnabled(true);
       }    
    }//GEN-LAST:event_jButton6MouseClicked

    private void btndeletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeletMouseClicked
        dTM.removeRow(tblprintDetails.getSelectedRow());
        btndelet.setEnabled(false);
    }//GEN-LAST:event_btndeletMouseClicked

    private void btnprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintMouseClicked
       int prcount=tblprintDetails.getRowCount();
    if(prcount>0)
    {
        DefaultTableModel tableModel=(DefaultTableModel)tblprintDetails.getModel();
        try {
             HashMap<String, Object> para=new HashMap<>();
             para.put("tittle","Sale Report");
            // TableModelData();
             JasperPrint jasperPrint = null;
             JasperCompileManager.compileReportToFile("C:\\Users\\ccs\\Documents\\NetBeansProjects\\Inventory\\src\\report\\sellReport.jrxml");
             jasperPrint = JasperFillManager.fillReport("C:\\Users\\ccs\\Documents\\NetBeansProjects\\Inventory\\src\\report\\sellReport.jasper", para,
             new JRTableModelDataSource(tableModel));
             JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    else
    {
        JOptionPane.showMessageDialog(rootPane, "Not Details to print");
    }    
    }//GEN-LAST:event_btnprintMouseClicked
    private void lordBtnDissable()
    {
        btnsave.setEnabled(false);
        btndelet.setEnabled(false);
        btnprint.setEnabled(false);
    }
    
    private void tabletest()
    {
          String source = "C:\\Users\\Ruwan\\Documents\\NetBeansProjects\\Inventory\\src\\report\\test.jrxml";
          try {
            //////////////////////
            DefaultTableModel tableModel = null;
          //  TableModelData();
            JasperPrint jasperPrint = null;
            JasperCompileManager.compileReportToFile("C:\\Users\\Ruwan\\Documents\\NetBeansProjects\\Inventory\\src\\report\\test.jrxml");
            jasperPrint = JasperFillManager.fillReport("C:\\Users\\Ruwan\\Documents\\NetBeansProjects\\Inventory\\src\\report\\test.jasper", new HashMap(),
            new JRTableModelDataSource(tableModel));
            JasperViewer.viewReport(jasperPrint, false);
            /////////////////////
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }    
    }
//    //test only
//    private void TableModelData() {
//        String[] columnNames = {"aaaa", "bbbb", "cccc", "dddd"};
//        String[][] data = {
//            {"111", "G Conger", " Orthopaedic", "jim@wheremail.com"},
//            {"222", "A Date", "ENT", "adate@somemail.com"},
//            {"333", "R Linz", "Paedriatics", "rlinz@heremail.com"},
//            {"444", "V Sethi", "Nephrology", "vsethi@whomail.com"},
//            {"555", "K Rao", "Orthopaedics", "krao@whatmail.com"},
//            {"666", "V Santana", "Nephrology", "vsan@whenmail.com"},
//            {"777", "J Pollock", "Nephrology", "jpol@domail.com"},
//            {"888", "H David", "Nephrology", "hdavid@donemail.com"},
//            {"999", "P Patel", "Nephrology", "ppatel@gomail.com"},
//            {"101", "C Comer", "Nephrology", "ccomer@whymail.com"}
//        };
//    
//       DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
//    }
    
    private void saleFilter()
    {
        String saleFDate=((JTextField)fromDate.getDateEditor().getUiComponent()).getText();
        String saleTDate=((JTextField)toDate.getDateEditor().getUiComponent()).getText();
        if(saleFDate.length()>0 && saleTDate.isEmpty())
        {
         try {
            reportSql="SELECT sin as 'SALE NO', date as 'DATE',sale_income as 'AMOUNT' from payment where date='"+saleFDate+"'";
            pst1=conn1.prepareStatement(reportSql);
            rs1=pst1.executeQuery();
            tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs1));
            int tr=tblsale.getRowCount();
            txttransaction.setText(Integer.toString(tr));
            if(tr>0)
            {
            calCost();
            }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "Empty Record");
            }
         } 
            catch (Exception e) {
                 JOptionPane.showMessageDialog(rootPane, "frist date");
                                }
        }
     
        else if(saleFDate.length()>0 && saleTDate.length()>0)
        {
        try {
            reportSql="SELECT sin as 'SALE NO', date as 'DATE',sale_income as 'AMOUNT' from payment where date between'"+saleFDate+"' and '"+saleTDate+"' ";
            pst1=conn1.prepareStatement(reportSql);
            rs1=pst1.executeQuery();
            tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs1));
            
            int tr=tblsale.getRowCount();
           txttransaction.setText(Integer.toString(tr));
                  if(tr>0)
                 {
                calCost2();
                 }
                 else
                 {
                 JOptionPane.showMessageDialog(rootPane, "Empty Record");
                 } 
         } catch (Exception e) {
              JOptionPane.showMessageDialog(rootPane, e);
                                }
           }
        else
        {
          JOptionPane.showMessageDialog(rootPane, "Select date to filter data");  
        }    
    }
    
    private  void  calCost()
    {
     String saleFDate=((JTextField)fromDate.getDateEditor().getUiComponent()).getText();
        try {
            String sq="SELECT sum(sale_income),sum(sale_cost),sum(sale_return),sum(return_cost) from payment where date='"+saleFDate+"'";
            pst=conn.prepareStatement(sq);
            rs=pst.executeQuery();
           while(rs.next())
           {
               
            String sValue=rs.getString("sum(sale_income)");
            String sCost=rs.getString("sum(sale_cost)");
            Double reInc=Double.parseDouble(rs.getString("sum(sale_return)"));
            Double reCos=Double.parseDouble(rs.getString("sum(return_cost)"));
            Double sCo=Double.parseDouble(sCost);
            Double sVa=Double.parseDouble(sValue);
            Double rebal=reInc-reCos;
            Double nBal=sVa-sCo;
            Double netSale=sVa-reInc;
            
            Double netIncome=nBal-rebal;
            JOptionPane.showMessageDialog(rootPane, reCos);
            txtsalesum.setText(netSale.toString());
            txtincome.setText(netIncome.toString());
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
    
    }
     private  void  calCost2()
    {
     String saleFDate=((JTextField)fromDate.getDateEditor().getUiComponent()).getText();
     String saleTDate=((JTextField)toDate.getDateEditor().getUiComponent()).getText();
        try {
            String sq="SELECT sum(sale_income),sum(sale_cost),sum(sale_return),sum(return_cost) from payment where date between'"+saleFDate+"' and '"+saleTDate+"'";
            pst=conn.prepareStatement(sq);
            rs=pst.executeQuery();
           while(rs.next())
           {
            String sValue=rs.getString("sum(sale_income)");
            String sCost=rs.getString("sum(sale_cost)");
            Double reInc=Double.parseDouble(rs.getString("sum(sale_return)"));
            Double reCos=Double.parseDouble(rs.getString("sum(return_cost)"));
            Double sCo=Double.parseDouble(sCost);
            Double sVa=Double.parseDouble(sValue);
            Double rebal=reInc-reCos;
            Double nBal=sVa-sCo;
            Double netSale=sVa-reInc;
            Double netIncome=nBal-rebal;
            JOptionPane.showMessageDialog(rootPane, reCos);
            txtsalesum.setText(netSale.toString());
            txtincome.setText(netIncome.toString());  
            }
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(rootPane, e);
            }    
    }
    
    private void fClear()
    {
        ((JTextField)fromDate.getDateEditor().getUiComponent()).setText("");
        ((JTextField)toDate.getDateEditor().getUiComponent()).setText("");
        txtsalesum.setText("0.0");
        txttransaction.setText("0");
        txtincome.setText("0.0");
        saleLord();
    }
            
     private void  theader()
    {
    JTableHeader thead = tblprintDetails.getTableHeader();
       thead.setForeground(Color.BLUE);
       thead.setFont(new Font("Tahome", Font.BOLD, 14));
       TableColumn col1=tblprintDetails.getColumnModel().getColumn(0);
       col1.setPreferredWidth(130);
    }
    
   private void saleLord()
    {
    try {
        String sql="SELECT sin as 'SALE NO', date as 'DATE',sale_income as 'AMOUNT' from payment";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnclear;
    private javax.swing.JPanel btndelet;
    private javax.swing.JPanel btnprint;
    private javax.swing.JPanel btnsave;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JPanel jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblprintDetails;
    private javax.swing.JTable tblsale;
    private com.toedter.calendar.JDateChooser toDate;
    private javax.swing.JTextField txtincome;
    private javax.swing.JTextField txtsalesum;
    private javax.swing.JTextField txttransaction;
    // End of variables declaration//GEN-END:variables
}
