/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruwan
 */
public class saleReturn extends javax.swing.JInternalFrame {

    /**
     * Creates new form saleReturn
     */
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    DefaultTableModel dTM=new DefaultTableModel();
    Object[] row=new Object[7];
    Object[] column={"SIN","Re No","Item Number","Iten Name","Quentity","Price","Amount"};
    String itQua;
    String itPri;
    String toPri;
    String cost;
    Double singleItemCost;
    Double singleItemReturnCost;
    Double reQue=0.0;
    Double allValue=0.0;
    Double allCost=0.0;
    String aValue;
    String aCost;
           
   
    
    public saleReturn() {
        initComponents();
        conn=DBConnect.connect();
        btbreturn.setEnabled(false);
        btnreall.setEnabled(false);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReturnCon = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSaleLord = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtItNum = new javax.swing.JTextField();
        txtItName = new javax.swing.JTextField();
        txtTotPrice = new javax.swing.JTextField();
        txtque = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btbreturn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnreall = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtbill = new javax.swing.JTextField();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(880, 510));
        setPreferredSize(new java.awt.Dimension(880, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tblReturnCon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblReturnCon);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 300, 540, 160);

        tblSaleLord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSaleLord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSaleLordMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSaleLord);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 540, 170);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel7.setText("Item Number");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(610, 100, 91, 18);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel8.setText("Iten Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(610, 140, 72, 18);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(610, 180, 61, 18);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sales Return");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 20, 150, 20);

        txtItNum.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txtItNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItNumActionPerformed(evt);
            }
        });
        jPanel1.add(txtItNum);
        txtItNum.setBounds(710, 90, 130, 30);

        txtItName.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(txtItName);
        txtItName.setBounds(710, 130, 130, 30);

        txtTotPrice.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txtTotPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotPrice);
        txtTotPrice.setBounds(710, 210, 130, 30);

        txtque.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txtque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqueActionPerformed(evt);
            }
        });
        txtque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtqueKeyReleased(evt);
            }
        });
        jPanel1.add(txtque);
        txtque.setBounds(710, 170, 130, 30);

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel12.setText("Total Price");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(610, 220, 80, 18);

        btbreturn.setBackground(new java.awt.Color(193, 222, 136));
        btbreturn.setPreferredSize(new java.awt.Dimension(90, 40));
        btbreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbreturnMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rotate-24.png"))); // NOI18N
        jLabel17.setText("Return");

        javax.swing.GroupLayout btbreturnLayout = new javax.swing.GroupLayout(btbreturn);
        btbreturn.setLayout(btbreturnLayout);
        btbreturnLayout.setHorizontalGroup(
            btbreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btbreturnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btbreturnLayout.setVerticalGroup(
            btbreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btbreturnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jPanel1.add(btbreturn);
        btbreturn.setBounds(730, 330, 90, 40);

        btnreall.setBackground(new java.awt.Color(193, 222, 136));
        btnreall.setPreferredSize(new java.awt.Dimension(90, 40));
        btnreall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreallMouseClicked(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(193, 222, 136));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/undo-4-24.png"))); // NOI18N
        jLabel16.setText("Return All");

        javax.swing.GroupLayout btnreallLayout = new javax.swing.GroupLayout(btnreall);
        btnreall.setLayout(btnreallLayout);
        btnreallLayout.setHorizontalGroup(
            btnreallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
            .addGroup(btnreallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnreallLayout.createSequentialGroup()
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnreallLayout.setVerticalGroup(
            btnreallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(btnreallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnreallLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(btnreall);
        btnreall.setBounds(620, 330, 100, 40);

        jButton4.setBackground(new java.awt.Color(193, 222, 136));
        jButton4.setPreferredSize(new java.awt.Dimension(90, 40));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(193, 222, 136));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/brush-24.png"))); // NOI18N
        jLabel15.setText("Clear");

        javax.swing.GroupLayout jButton4Layout = new javax.swing.GroupLayout(jButton4);
        jButton4.setLayout(jButton4Layout);
        jButton4Layout.setHorizontalGroup(
            jButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButton4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jButton4Layout.setVerticalGroup(
            jButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButton4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jButton4);
        jButton4.setBounds(730, 400, 90, 40);

        jButton3.setBackground(new java.awt.Color(193, 222, 136));
        jButton3.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel13.setBackground(new java.awt.Color(193, 222, 136));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-24.png"))); // NOI18N
        jLabel13.setText("Delete");

        javax.swing.GroupLayout jButton3Layout = new javax.swing.GroupLayout(jButton3);
        jButton3.setLayout(jButton3Layout);
        jButton3Layout.setHorizontalGroup(
            jButton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButton3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jButton3Layout.setVerticalGroup(
            jButton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButton3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jButton3);
        jButton3.setBounds(620, 400, 100, 40);

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(600, 300, 240, 160);

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(600, 80, 250, 170);

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 280, 840, 200);

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 840, 200);

        jPanel2.setBackground(new java.awt.Color(193, 222, 136));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bill No");

        txtbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbillActionPerformed(evt);
            }
        });
        txtbill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbillKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(592, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(txtbill, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbill, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 10, 840, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbillActionPerformed

    private void txtqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqueActionPerformed

    private void txtItNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItNumActionPerformed

    private void txtTotPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotPriceActionPerformed

    private void txtbillKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbillKeyReleased
            saleLord();
            if(tblSaleLord.getRowCount()>0)
                {
                    btnreall.setEnabled(true);
                    btbreturn.setEnabled(false);
                }
    }//GEN-LAST:event_txtbillKeyReleased
 
    private void allReturn()
    {
     try {
             String sqt="SELECT sale_income,sale_cost FROM `payment` WHERE sin='"+txtbill.getText()+"'";
             pst=conn.prepareStatement(sqt);
             rs=pst.executeQuery();
             if(rs.next())
             {
             aValue=rs.getString("sale_income");
             aCost=rs.getString("sale_cost");
             JOptionPane.showMessageDialog(rootPane, allCost);
             }
         }
     catch (Exception e) 
     {
            JOptionPane.showMessageDialog(rootPane, e);
     }
    }
   
    private void balanceCost()
    {
      try {
             String sqt="SELECT sale_cost FROM `payment` WHERE sin='"+txtbill.getText()+"'";
             pst=conn.prepareStatement(sqt);
             rs=pst.executeQuery();
                if(rs.next())
                {
                    cost =rs.getString("sale_cost");
                   // JOptionPane.showMessageDialog(rootPane, cost);
                }
           //JOptionPane.showMessageDialog(rootPane, cost);  
           } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
             }
     }
    
//    private void addCost()
//     {
//      try {
//             String sql="INSERT INTO `returnsalecost`(`sin`, `cost`) VALUES ('"+txtbill.getText()+"','"+cost+"')";
//             pst=conn.prepareStatement(sql);
//             pst.execute();
//          //  JOptionPane.showMessageDialog(rootPane,"Item added successfully");
//         } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "insert error");
//            }
//     }
    
     private void itemreturnbalancetopayment()
     {
         Double reValue=Double.parseDouble(txtTotPrice.getText());
         Double recos=Double.valueOf(singleItemReturnCost);
            try {
              String squpdate = "UPDATE payment SET sale_return= sale_return+'"+reValue+"',return_cost=return_cost+'"+recos+"' WHERE sin='"+txtbill.getText()+"'";
              pst=conn.prepareStatement(squpdate);
              pst.execute();
            } catch (Exception e) {
              JOptionPane.showMessageDialog(rootPane, e);
              }
      }
     
     private void allReturnbalance()
     {
         Double allreValue=Double.parseDouble(aValue);
         Double allrecos=Double.parseDouble(aCost);
         try {
              String squpdate = "UPDATE payment SET sale_return= sale_return+'"+allreValue+"', return_cost=return_cost+'"+allrecos+"' WHERE sin='"+txtbill.getText()+"'";
              pst=conn.prepareStatement(squpdate);
              pst.execute();
               // JOptionPane.showMessageDialog(rootPane, "update success");
         } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
         }
     }
     
     private void updatesale()
    {
        try {
             String squpdate = "UPDATE sells SET quentity=quentity -'"+txtque.getText()+"',amount=amount -'"+txtTotPrice.getText()+"' WHERE sin='"+txtbill.getText()+"' and item_number='"+txtItNum.getText()+"'";
             pst=conn.prepareStatement(squpdate);
             pst.execute();  
             JOptionPane.showMessageDialog(rootPane, "return update");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
            }
    }
     
      private void updatepayment()
    {
        try {
            
            
             String squpdate = "UPDATE payment SET sale_income=sale_income -'"+txtTotPrice.getText()+"' WHERE sin='"+txtbill.getText()+"'";
             pst=conn.prepareStatement(squpdate);
             pst.execute();  
             JOptionPane.showMessageDialog(rootPane, "return update");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
            }
    }
     
     
     private void addSingleItemCost()
     {
      try {
             String sql="INSERT INTO `returnsalecost`(`sin`, `cost`) VALUES ('"+txtbill.getText()+"','"+singleItemReturnCost+"')";
              pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "insert error");
        }
     }
    
    private void clear()
    {
        txtItName.setText("");
        txtItNum.setText("");
        txtque.setText("");
        txtTotPrice.setText("");
    }
   
    private void saleReturnAdd()
    {
        try {
             String qr= "INSERT INTO `sale_return`(`sin`, `receive_no`, `item_no`, `item_name`, `quantity`, `price`, `amount`,mark) VALUES ('"+row[0]+"','"+row[1]+"','"+row[2]+"','"+row[3]+"','"+row[4]+"','"+row[5]+"','"+row[6]+"','1')";
           
            pst=conn.prepareStatement(qr);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }
    
    private void allsaleReturnAdd()
    {
        
        int selectrowindex=tblSaleLord.getSelectedRow();
        DefaultTableModel tmodel=(DefaultTableModel)tblReturnCon.getModel();
        Object[] rows=new Object[7];
        for(int x=0; x<tblReturnCon.getRowCount(); x++)
        {
              rows[0]=(tmodel.getValueAt(x, 0).toString());
              rows[1]=(tmodel.getValueAt(x, 1).toString());
              rows[2]=(tmodel.getValueAt(x, 2).toString());
              rows[3]=(tmodel.getValueAt(x, 3).toString());
              rows[4]=(tmodel.getValueAt(x, 4).toString());
              rows[5]=(tmodel.getValueAt(x, 5).toString());
              rows[6]=(tmodel.getValueAt(x, 6).toString());
        try {
             String qr= "INSERT INTO `sale_return`(`sin`, `receive_no`, `item_no`, `item_name`, `quantity`, `price`, `amount`,mark) VALUES ('"+rows[0]+"','"+rows[1]+"','"+rows[2]+"','"+rows[3]+"','"+rows[4]+"','"+rows[5]+"','"+rows[6]+"','1')";
             pst=conn.prepareStatement(qr);
             pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
        }
    }
    
    private void tblSaleLordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSaleLordMouseClicked
       DefaultTableModel tmodel=(DefaultTableModel)tblSaleLord.getModel();
        int selectrowindex=tblSaleLord.getSelectedRow();
        String itNum=(tmodel.getValueAt(selectrowindex, 2).toString());
        String itName=(tmodel.getValueAt(selectrowindex, 3).toString());
        String que=(tmodel.getValueAt(selectrowindex, 4).toString());
        String totp=(tmodel.getValueAt(selectrowindex, 6).toString());
        txtItNum.setText(itNum);
        txtItName.setText(itName);
        txtque.setText(que);
        txtTotPrice.setText(totp);
        
        itPri=(tmodel.getValueAt(selectrowindex, 5).toString());
        itQua=(tmodel.getValueAt(selectrowindex, 4).toString());
        toPri=(tmodel.getValueAt(selectrowindex, 6).toString());
        btbreturn.setEnabled(true);
        btnreall.setEnabled(false);
        itemCostSelect();
    }//GEN-LAST:event_tblSaleLordMouseClicked

    private void itemCostSelect()
    {
        DefaultTableModel tmodel=(DefaultTableModel)tblSaleLord.getModel();
        int selecrow=tblSaleLord.getSelectedRow();
        String reNum=(tmodel.getValueAt(selecrow, 1).toString());
        try{
             String sqt="SELECT buying_price FROM `receivestock` WHERE receive_no='"+reNum+"'";
             pst=conn.prepareStatement(sqt);
             rs=pst.executeQuery();
             if(rs.next())
             {
             singleItemCost =Double.valueOf(rs.getString("buying_price"));
             }
             singleItemReturnCost=singleItemCost; 
             } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
             }
    }
     
    private void txtqueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqueKeyReleased
      
     if(txtque.getText().length()>0)
     {
        Double itprice=Double.parseDouble(itPri);
        Double itQuentity=Double.parseDouble(itQua);
        Double totPrice;

        Double enQuentity=Double.parseDouble(txtque.getText());
        totPrice=enQuentity*itprice;
        txtTotPrice.setText(totPrice.toString());
        returnCostCal();
     }   
    }//GEN-LAST:event_txtqueKeyReleased

    private void returnCostCal()
    {
        reQue=Double.valueOf(txtque.getText());
        singleItemReturnCost=singleItemCost*reQue;
    }
    
    private void btnreallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreallMouseClicked
       //        allReturn();
//        try {
//                String sql="SELECT `sin`, `receive_no`, `item_number`, `item_name`, `quentity`, `price`, `amount` FROM `sells` where sin='"+txtbill.getText()+"'";
//                pst=conn.prepareStatement(sql);
//                rs=pst.executeQuery();
//                tblReturnCon.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(rootPane, e);
//                                  }
//        allsaleReturnAdd();
//        clear();
//        btnreall.setEnabled(false);
//        balanceCost();
//       // addCost();
//        allReturnbalance();
//        txtbill.setText("");
//        saleLord();
    }//GEN-LAST:event_btnreallMouseClicked

    private void btbreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbreturnMouseClicked
        dTM.setColumnIdentifiers(column);
        tblReturnCon.setModel(dTM);
        DefaultTableModel tmodel=(DefaultTableModel)tblSaleLord.getModel();
        int selectrowindex=tblSaleLord.getSelectedRow();
        try {
              row[0]=(tmodel.getValueAt(selectrowindex, 0).toString());
              row[1]=(tmodel.getValueAt(selectrowindex, 1).toString());
              row[2]=(tmodel.getValueAt(selectrowindex, 2).toString());
              row[3]=(tmodel.getValueAt(selectrowindex, 3).toString());
              row[4]=txtque.getText();
              row[5]=(tmodel.getValueAt(selectrowindex, 5).toString());
              row[6]=txtTotPrice.getText();
              dTM.addRow(row);
              saleReturnAdd();
              
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        updatesale();
      //  updatepayment();
        addSingleItemCost();
        itemreturnbalancetopayment();
        clear();
        btbreturn.setEnabled(false);
    }//GEN-LAST:event_btbreturnMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        clear();
        txtbill.setText("");
        saleLord();
    }//GEN-LAST:event_jButton4MouseClicked

    private void saleLord()
    {
        try {
            String sql="SELECT `sin`, `receive_no`, `item_number`, `item_name`, `quentity`, `price`, `amount` FROM `sells` where sin='"+txtbill.getText()+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblSaleLord.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btbreturn;
    private javax.swing.JPanel btnreall;
    private javax.swing.JPanel jButton3;
    private javax.swing.JPanel jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblReturnCon;
    private javax.swing.JTable tblSaleLord;
    private javax.swing.JTextField txtItName;
    private javax.swing.JTextField txtItNum;
    private javax.swing.JTextField txtTotPrice;
    private javax.swing.JTextField txtbill;
    private javax.swing.JTextField txtque;
    // End of variables declaration//GEN-END:variables
}
