/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.lang.*;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Ruwan
 */
public class Setting extends javax.swing.JInternalFrame {

    /**
     * Creates new form Setting
     */
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
      
    public Setting() {
        initComponents();        
        conn=DBConnect.connect();
        autoId();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblimage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtuid = new javax.swing.JTextField();
        txtuname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtposition = new javax.swing.JTextField();
        txtpword = new javax.swing.JTextField();
        txtconpword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnregister = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnbrows = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(880, 510));
        setPreferredSize(new java.awt.Dimension(880, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lblimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(lblimage);
        lblimage.setBounds(670, 130, 170, 140);

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel5.setText("Registation Details");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 90, 180, 20);

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 80, 350, 40);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel7.setText("User Id");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 160, 80, 18);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel8.setText("User Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 200, 80, 18);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel9.setText("First Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 240, 76, 18);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel10.setText("Last Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(300, 280, 74, 18);

        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel11.setText("Position");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(300, 320, 56, 18);

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel12.setText("Password");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(300, 360, 67, 18);

        jLabel13.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel13.setText("Confirm Password");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(300, 400, 126, 18);

        txtuid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuidActionPerformed(evt);
            }
        });
        txtuid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuidKeyPressed(evt);
            }
        });
        jPanel1.add(txtuid);
        txtuid.setBounds(440, 160, 170, 25);

        txtuname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtuname);
        txtuname.setBounds(440, 200, 170, 25);

        txtfname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtfname);
        txtfname.setBounds(440, 240, 170, 25);

        txtlname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtlname);
        txtlname.setBounds(440, 280, 170, 25);

        txtposition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpositionActionPerformed(evt);
            }
        });
        jPanel1.add(txtposition);
        txtposition.setBounds(440, 320, 170, 25);

        txtpword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtpword);
        txtpword.setBounds(440, 360, 170, 25);

        txtconpword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtconpword);
        txtconpword.setBounds(440, 400, 170, 25);

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 120, 350, 340);

        jLabel15.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel15.setText("Picture");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(660, 90, 80, 23);

        jButton3.setBackground(new java.awt.Color(193, 222, 136));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rotate-24.png"))); // NOI18N
        jLabel1.setText("Update");

        javax.swing.GroupLayout jButton3Layout = new javax.swing.GroupLayout(jButton3);
        jButton3.setLayout(jButton3Layout);
        jButton3Layout.setHorizontalGroup(
            jButton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jButton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jButton3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jButton3Layout.setVerticalGroup(
            jButton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jButton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jButton3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jButton3);
        jButton3.setBounds(650, 410, 90, 40);

        jButton5.setBackground(new java.awt.Color(193, 222, 136));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-24.png"))); // NOI18N
        jLabel2.setText("Delete");

        javax.swing.GroupLayout jButton5Layout = new javax.swing.GroupLayout(jButton5);
        jButton5.setLayout(jButton5Layout);
        jButton5Layout.setHorizontalGroup(
            jButton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jButton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jButton5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jButton5Layout.setVerticalGroup(
            jButton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jButton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jButton5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jButton5);
        jButton5.setBounds(760, 410, 90, 40);

        jButton4.setBackground(new java.awt.Color(193, 222, 136));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/star-24.png"))); // NOI18N
        jLabel17.setText("Select");

        javax.swing.GroupLayout jButton4Layout = new javax.swing.GroupLayout(jButton4);
        jButton4.setLayout(jButton4Layout);
        jButton4Layout.setHorizontalGroup(
            jButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jButton4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jButton4Layout.setVerticalGroup(
            jButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jButton4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jButton4);
        jButton4.setBounds(650, 350, 90, 40);

        btnregister.setBackground(new java.awt.Color(193, 222, 136));
        btnregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregisterMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-image-24.png"))); // NOI18N
        jLabel19.setText("Register");

        javax.swing.GroupLayout btnregisterLayout = new javax.swing.GroupLayout(btnregister);
        btnregister.setLayout(btnregisterLayout);
        btnregisterLayout.setHorizontalGroup(
            btnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(btnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnregisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnregisterLayout.setVerticalGroup(
            btnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(btnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnregisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnregister);
        btnregister.setBounds(760, 350, 90, 40);

        btnbrows.setBackground(new java.awt.Color(193, 222, 136));
        btnbrows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbrowsMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-12-24.png"))); // NOI18N
        jLabel20.setText("Brows");

        javax.swing.GroupLayout btnbrowsLayout = new javax.swing.GroupLayout(btnbrows);
        btnbrows.setLayout(btnbrowsLayout);
        btnbrowsLayout.setHorizontalGroup(
            btnbrowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(btnbrowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnbrowsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnbrowsLayout.setVerticalGroup(
            btnbrowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnbrowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnbrowsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnbrows);
        btnbrows.setBounds(670, 280, 170, 30);

        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel18);
        jLabel18.setBounds(640, 330, 220, 130);

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(640, 120, 220, 200);

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(640, 80, 220, 40);

        jPanel2.setBackground(new java.awt.Color(193, 222, 136));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Administor Setting");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(280, 20, 580, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpositionActionPerformed

    private void txtuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuidActionPerformed

    private void autoId()
    {
        try {
            String sql="SELECT user_id FROM admin ORDER BY user_id DESC LIMIT 1";          
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next())
           {
               String rnno=rs.getString("user_id");
               int co=rnno.length();
               String txt= rnno.substring(0, 3);
               String num=rnno.substring(3, co);
               int n=Integer.parseInt(num);
               n++;
               String snum=Integer.toString(n);
               String ftxt=txt+snum;
               txtuid.setText(ftxt);
           }
            else
           {
               txtuid.setText("UID1000");
           }                           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }       
    }
    
    private void clearField()
    {
    txtuname.setText("");
    txtfname.setText("");
    txtlname.setText("");
    txtposition.setText("");
    txtpword.setText("");
    txtconpword.setText("");
    lblimage.setText("");        
    }
        
    private  void fieldClear()
    {
    txtuname.setText("");
    txtfname.setText("");
    txtlname.setText("");
    txtposition.setText("");
    txtpword.setText("");
    txtconpword.setText("");
    lblimage.setDisabledIcon(frameIcon);
    }
    
     
  
    
    private void delete()
    {
         int x=JOptionPane.showConfirmDialog(rootPane, "Do you realy want to delete");
         if(x==0)
         {
         try {
                String sql="DELETE FROM admin where user_id='"+ txtuid.getText() +"'";
                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(rootPane, "successfully delete");                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }    
    }
    private void txtuidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuidKeyPressed
       fieldClear();
    }//GEN-LAST:event_txtuidKeyPressed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int x=JOptionPane.showConfirmDialog(rootPane, "Do you realy want to update");
        if(x==0)
        {
         String uid=txtuid.getText();
        String una=txtuname.getText();
        String fna=txtfname.getText();
        String lna=txtlname.getText();
        String pos=txtposition.getText();
        String psw=txtpword.getText();
        String cpw=txtconpword.getText();
        try {
              String squpdate = "UPDATE `admin` SET `user_name`=?,`first_name`=?,`last_name`=?,`pisition`=?,`password`=?,`confirm_password`=?,`image`=? WHERE user_id='"+txtuid.getText()+"'";
              pst=conn.prepareStatement(squpdate);               
                pst.setString(1, una);
                pst.setString(2, fna);
                pst.setString(3, lna);
                pst.setString(4, pos);
                pst.setString(5, psw);
                pst.setString(6, cpw);
                pst.setBytes(7, pimage);                
                pst.execute(); 
                JOptionPane.showMessageDialog(rootPane,"successfuly update");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,e);              
            }   
        }
        autoId();
        fieldClear();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
       delete();
        autoId();
        fieldClear();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
       try {
            String sql="SELECT `user_id`, `user_name`, `first_name`, `last_name`, `pisition`, `password`, `confirm_password`, `image` FROM admin where user_id='"+txtuid.getText()+"'";          
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next())
           {
               txtuname.setText(rs.getString("user_name"));
               txtfname.setText(rs.getString("first_name"));
               txtlname.setText(rs.getString("last_name"));
               txtposition.setText(rs.getString("pisition"));
               txtpword.setText(rs.getString("password"));
               txtconpword.setText(rs.getString("confirm_password"));
               byte[] imagedata=rs.getBytes("image");
               format=new ImageIcon(imagedata);
               Image mm=format.getImage();
               Image img2=mm.getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH);
               ImageIcon image=new ImageIcon(img2);
               lblimage.setIcon(image);
            }                            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }       
    }//GEN-LAST:event_jButton4MouseClicked

    private void btnregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregisterMouseClicked
       String uid=txtuid.getText();
        String una=txtuname.getText();
        String fna=txtfname.getText();
        String lna=txtlname.getText();
        String pos=txtposition.getText();
        String psw=txtpword.getText();
        String cpw=txtconpword.getText();        
        if(psw.equals(cpw) && uid.length()!=0 && una.length() !=0 && fna.length() !=0 && lna.length()!=0 && pos.length()!=0 && psw.length() !=0 && cpw.length()!=0)
           {               
                try {
                String q= "INSERT INTO `admin` ( user_id,`user_name`, `first_name`, `last_name`, `pisition`, `password`, `confirm_password`,`image`) VALUES (?,?,?,?,?,?,?,?)";               
                pst=conn.prepareStatement(q);                
                pst.setString(1, uid);
                pst.setString(2, una);
                pst.setString(3, fna);
                pst.setString(4, lna);
                pst.setString(5, pos);
                pst.setString(6, psw);
                pst.setString(7, cpw);
                pst.setBytes(8, pimage);                
                pst.execute(); 
                    } 
                catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,e);
                                          }  
               //       
           }
         
        else
        {
            JOptionPane.showMessageDialog(rootPane,"correctly fill");
        }
        JOptionPane.showMessageDialog(rootPane,"registation success");      
        autoId();
        clearField();
    }//GEN-LAST:event_btnregisterMouseClicked

    private void btnbrowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbrowsMouseClicked
        JFileChooser fchoser=new JFileChooser();
        fchoser.showOpenDialog(null);
        File f=fchoser.getSelectedFile();
        fname=f.getAbsolutePath();
        ImageIcon micon=new ImageIcon(fname);        
        try {
            File image=new File(fname);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream baos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readnum; (readnum=fis.read(buf)) !=-1;)
            {            
                baos.write(buf,0,readnum);                
            }
            pimage=baos.toByteArray();
            lblimage.setIcon(resizeImage(fname, buf));
        } catch (Exception e) {
        }        
    }//GEN-LAST:event_btnbrowsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnbrows;
    private javax.swing.JPanel btnregister;
    private javax.swing.JPanel jButton3;
    private javax.swing.JPanel jButton4;
    private javax.swing.JPanel jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextField txtconpword;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtposition;
    private javax.swing.JTextField txtpword;
    private javax.swing.JTextField txtuid;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables

private ImageIcon format=null;
String fname=null;
int s=0;
byte[] pimage=null;

      public ImageIcon resizeImage(String imagePath, byte[] pic){
          
        ImageIcon myImage=null;
        if(imagePath !=null)
        {
        myImage=new ImageIcon(imagePath);
        
        }else{
         myImage=new ImageIcon(pic);
        }
                
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lblimage.getHeight(), lblimage.getWidth(),  Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    } 

}
